"""Source-faithful XSTAR-to-Python port infrastructure.

This package is intentionally separate from the historical audit modules.  It
tracks the original XSTAR source tree, preserves stage/routine provenance, and
provides an executable driver that can be filled in source order.
"""

from .inventory import (
    FortranSourceFile,
    FortranRoutine,
    XSTARSourceInventory,
    build_source_inventory,
    write_source_inventory,
)
from .ledger import (
    PortStatus,
    PortLedgerEntry,
    XSTARPortLedger,
    default_port_ledger,
)
from .runtime import (
    FortranArray,
    FortranRuntimeError,
    fortran_nint,
    fortran_sign,
    fortran_mod,
)
from .state import (
    XSTARAtomicState,
    XSTARPlasmaState,
    XSTARRadiationState,
    XSTARMatrixState,
    XSTARThermalState,
    XSTARTransferState,
    XSTARPythonState,
)
from .driver import (
    XSTARStage,
    UnportedXSTARRoutine,
    XSTARPythonDriver,
)
from .atomic_database import (
    AtomicDatabaseError,
    PackedRecordHeader,
    FortranPackedVector,
    FortranPointerTable,
    XSTARMasterData,
    XSTARDerivedPointers,
    AtomicDatabaseBuildResult,
    DBWK2Instruction,
    DBWK2Result,
    readtbl,
    setptrs,
    dbwk2,
    populate_atomic_state,
    load_atomic_database_state,
    register_atomic_database_stages,
    POINTER_CACHE_FORMAT_VERSION,
    atomic_database_fingerprint,
    save_derived_pointer_cache,
    load_derived_pointer_cache,
    write_atomic_database_products,
)


from .ucalc import (
    UCalcLevel,
    UCalcLevelTable,
    UCalcRecord,
    UCalcContext,
    UCalcStatus,
    UCalcProvenance,
    UCalcResult,
    UCalcExecutionError,
    UCalcUntranslatedBranch,
    UCalcBranchSpec,
    SourceFaithfulUCalc,
    complete_ucalc_branch_catalog,
    default_source_faithful_ucalc,
)
from .ucalc_inventory import (
    build_ucalc_data_type_inventory,
    build_ucalc_branch_catalog_rows,
    build_ucalc_index_only_samples,
    write_ucalc_subsystem_products,
)


from .linear_algebra import (
    XSTARLinearAlgebraError,
    LUDecomposition,
    LinearSolveResult,
    ludcmp,
    lubksb,
    mprove,
    leqt2f,
)


from .escape_state import (
    EscapeStateError,
    EscapeStateBuildResult,
    load_escape_state_from_xstar_run,
    write_escape_state_npz,
    write_escape_state_summary,
)

from .element_equilibrium import (
    ElementEquilibriumError,
    ElementIonBlock,
    ElementBasisRow,
    ElementCompactBasis,
    EscapeProbabilityContext,
    ElementEquilibriumContext,
    MatrixTerm,
    IonAssemblySummary,
    ElementMatrixAssembly,
    LucyIterationTrace,
    LucySolveResult,
    ElementEquilibriumResult,
    pescl,
    pescv,
    build_level_table,
    build_element_compact_basis,
    levwk,
    levwkelement,
    assemble_element_matrix,
    msolvelucy,
    solve_element_statistical_equilibrium,
    register_element_equilibrium_stage,
    write_element_equilibrium_products,
)


from .population_parity import (
    PopulationParityError,
    XSTARPopulationReference,
    PopulationMetrics,
    ElementPopulationParityResult,
    load_xstar_population_reference,
    compare_element_population_parity,
    write_element_population_parity_products,
)

from .msolvelucy_state_parity import (
    MSolveStateParityError,
    StateComponentMetrics,
    MSolveStateParityResult,
    compare_msolvelucy_state_probe,
    write_msolvelucy_state_parity_products,
)

from .full_element_matrix_parity import (
    FullElementMatrixParityError,
    MatrixFamilyParityMetrics,
    FullElementMatrixParityResult,
    compare_full_element_matrix_probe,
    write_full_element_matrix_parity_products,
)

from .ucalc_dispatch import (
    UCalcBranch,
    UCalcDispatcher,
    default_ucalc_dispatcher,
)

__all__ = [
    "FortranSourceFile",
    "FortranRoutine",
    "XSTARSourceInventory",
    "build_source_inventory",
    "write_source_inventory",
    "PortStatus",
    "PortLedgerEntry",
    "XSTARPortLedger",
    "default_port_ledger",
    "FortranArray",
    "FortranRuntimeError",
    "fortran_nint",
    "fortran_sign",
    "fortran_mod",
    "XSTARAtomicState",
    "XSTARPlasmaState",
    "XSTARRadiationState",
    "XSTARMatrixState",
    "XSTARThermalState",
    "XSTARTransferState",
    "XSTARPythonState",
    "XSTARStage",
    "UnportedXSTARRoutine",
    "XSTARPythonDriver",
    "UCalcLevel",
    "UCalcLevelTable",
    "UCalcRecord",
    "UCalcContext",
    "UCalcStatus",
    "UCalcProvenance",
    "UCalcResult",
    "UCalcExecutionError",
    "UCalcUntranslatedBranch",
    "UCalcBranchSpec",
    "SourceFaithfulUCalc",
    "complete_ucalc_branch_catalog",
    "default_source_faithful_ucalc",
    "build_ucalc_data_type_inventory",
    "build_ucalc_branch_catalog_rows",
    "build_ucalc_index_only_samples",
    "write_ucalc_subsystem_products",
    "UCalcBranch",
    "UCalcDispatcher",
    "default_ucalc_dispatcher",
    "AtomicDatabaseError",
    "PackedRecordHeader",
    "FortranPackedVector",
    "FortranPointerTable",
    "XSTARMasterData",
    "XSTARDerivedPointers",
    "AtomicDatabaseBuildResult",
    "DBWK2Instruction",
    "DBWK2Result",
    "readtbl",
    "setptrs",
    "dbwk2",
    "populate_atomic_state",
    "load_atomic_database_state",
    "register_atomic_database_stages",
    "POINTER_CACHE_FORMAT_VERSION",
    "atomic_database_fingerprint",
    "save_derived_pointer_cache",
    "load_derived_pointer_cache",
    "write_atomic_database_products",
    "XSTARLinearAlgebraError",
    "LUDecomposition",
    "LinearSolveResult",
    "ludcmp",
    "lubksb",
    "mprove",
    "leqt2f",
    "ElementEquilibriumError",
    "ElementIonBlock",
    "ElementBasisRow",
    "ElementCompactBasis",
    "EscapeProbabilityContext",
    "ElementEquilibriumContext",
    "MatrixTerm",
    "IonAssemblySummary",
    "ElementMatrixAssembly",
    "LucyIterationTrace",
    "LucySolveResult",
    "ElementEquilibriumResult",
    "pescl",
    "pescv",
    "build_level_table",
    "build_element_compact_basis",
    "levwk",
    "levwkelement",
    "assemble_element_matrix",
    "msolvelucy",
    "solve_element_statistical_equilibrium",
    "register_element_equilibrium_stage",
    "write_element_equilibrium_products",
    "PopulationParityError",
    "XSTARPopulationReference",
    "PopulationMetrics",
    "ElementPopulationParityResult",
    "load_xstar_population_reference",
    "compare_element_population_parity",
    "write_element_population_parity_products",
    "MSolveStateParityError",
    "StateComponentMetrics",
    "MSolveStateParityResult",
    "compare_msolvelucy_state_probe",
    "write_msolvelucy_state_parity_products",
    "FullElementMatrixParityError",
    "MatrixFamilyParityMetrics",
    "FullElementMatrixParityResult",
    "compare_full_element_matrix_probe",
    "write_full_element_matrix_parity_products",
    "EscapeStateError",
    "EscapeStateBuildResult",
    "load_escape_state_from_xstar_run",
    "write_escape_state_npz",
    "write_escape_state_summary",
]
