"""Source-faithful XSTAR-to-Python port infrastructure.

This package is intentionally separate from the historical audit modules.  It
tracks the original XSTAR source tree, preserves stage/routine provenance, and
provides an executable driver that can be filled in source order.
"""

from .inventory import (
    FortranSourceFile,
    FortranRoutine,
    XSTARSourceInventory,
    build_source_inventory,
    write_source_inventory,
)
from .ledger import (
    PORT_LEDGER_VERSION,
    COMPLETED_SOURCE_PORT_MILESTONES,
    NEXT_COHERENT_SOURCE_PORT_TARGET,
    PortStatus,
    PortLedgerEntry,
    XSTARPortLedger,
    default_port_ledger,
)
from .runtime import (
    FortranArray,
    FortranRuntimeError,
    fortran_nint,
    fortran_sign,
    fortran_mod,
)
from .state import (
    XSTARAtomicState,
    XSTARPlasmaState,
    XSTARRadiationState,
    XSTARMatrixState,
    XSTARThermalState,
    XSTARLocalZoneState,
    XSTARTransferState,
    XSTARPythonState,
)
from .driver import (
    XSTARSourceRoutine,
    XSTARCALC_SOURCE_ORDER,
    XSTARCALC_FIXED_STATE_ORDER,
    ZONE_SOURCE_ORDER,
    XSTARStage,
    UnportedXSTARSourceRoutine,
    UnportedXSTARRoutine,
    XSTARPythonDriver,
)
from .atomic_database import (
    AtomicDatabaseError,
    PackedRecordHeader,
    FortranPackedVector,
    FortranPointerTable,
    XSTARMasterData,
    XSTARDerivedPointers,
    AtomicDatabaseBuildResult,
    DBWK2Instruction,
    DBWK2Result,
    readtbl,
    setptrs,
    dbwk2,
    populate_atomic_state,
    load_atomic_database_state,
    register_atomic_database_stages,
    POINTER_CACHE_FORMAT_VERSION,
    atomic_database_fingerprint,
    save_derived_pointer_cache,
    load_derived_pointer_cache,
    write_atomic_database_products,
)


from .ucalc import (
    UCalcLevel,
    UCalcLevelTable,
    UCalcRecord,
    UCalcContext,
    UCalcStatus,
    UCalcProvenance,
    UCalcResult,
    UCalcExecutionError,
    UCalcUntranslatedBranch,
    UCalcBranchSpec,
    SourceFaithfulUCalc,
    complete_ucalc_branch_catalog,
    default_source_faithful_ucalc,
)
from .ucalc_inventory import (
    build_ucalc_data_type_inventory,
    build_ucalc_branch_catalog_rows,
    build_ucalc_index_only_samples,
    write_ucalc_subsystem_products,
)


from .linear_algebra import (
    XSTARLinearAlgebraError,
    LUDecomposition,
    LinearSolveResult,
    ludcmp,
    lubksb,
    mprove,
    leqt2f,
)


from .escape_state import (
    EscapeStateError,
    EscapeStateBuildResult,
    load_escape_state_from_xstar_run,
    write_escape_state_npz,
    write_escape_state_summary,
)

from .element_equilibrium import (
    ElementEquilibriumError,
    ElementIonBlock,
    ElementBasisRow,
    ElementCompactBasis,
    EscapeProbabilityContext,
    ElementEquilibriumContext,
    MatrixTerm,
    IonAssemblySummary,
    ElementMatrixAssembly,
    LucyIterationTrace,
    LucySolveResult,
    ElementEquilibriumResult,
    pescl,
    pescv,
    build_level_table,
    build_element_compact_basis,
    levwk,
    levwkelement,
    assemble_element_matrix,
    msolvelucy,
    solve_element_statistical_equilibrium,
    register_element_equilibrium_stage,
    write_element_equilibrium_products,
)



from .ion_balance import (
    IonBalanceError,
    CalcIonRatesContext,
    CalcIonRateContribution,
    CalcIonRatesResult,
    IoneqmResult,
    IstrucResult,
    IonStageLimitResult,
    calc_ion_rates,
    ioneqm,
    istruc,
    select_ion_stage_limits,
    calc_element_pre_matrix_balance,
)


from .compton import (
    XSTAR_COMPTON_NCOMP,
    XSTAR_COMPTON_EMC2_EV,
    XSTAR_COMPTON_KT_EV_PER_T4,
    XSTAR_THOMSON_CROSS_SECTION_CM2,
    XSTAR_ERG_PER_EV,
    ComptonPortError,
    ComptonTableState,
    CmpFncResult,
    Comp2Result,
    Comp2Context,
    Comp2ProbeReference,
    Comp2ParityResult,
    packaged_coheat_path,
    resolve_coheat_path,
    load_compton_table,
    hunt3_one_based,
    cmpfnc,
    comp2,
    comp2_continuum_result,
    load_comp2_probe_reference,
    compare_comp2_probe,
    write_comp2_parity_products,
)

from .v0438_regression import (
    V0438AllElementRegressionGate,
    validate_v0438_all_element_regression,
)

from .local_zone import (
    CalcHMCAllError,
    FixedStateElementRequest,
    FixedStateContinuumResult,
    FixedStateElementResult,
    FixedStateCalcHMCAllResult,
    resolve_calc_hmc_all_density,
    calc_hmc_all,
    register_fixed_state_calc_hmc_all,
    write_fixed_state_calc_hmc_all_products,
)

from .all_element_fixed_state import (
    AllElementFixedStateError,
    OxygenCall73RegressionGate,
    OXYGEN_CALL73_REQUIRED_TRUE_FIELDS,
    validate_oxygen_call73_regression,
    AllElementProbeElement,
    AllElementFixedStatePlan,
    AllElementFixedStateRun,
    load_all_element_fixed_state_plan,
    build_all_element_fixed_state_requests,
    run_all_element_fixed_state,
    write_all_element_fixed_state_products,
)

from .calc_hmc_all_closure import (
    ElementXSTARVectorClosure,
    XSTARVectorMatrixClosureResult,
    build_xstar_vector_matrix_closure,
)

from .calc_hmc_all_matrix_parity import (
    SameCallMatrixParityResult,
    ThermalFamilyParityResult,
    Rate7CJ2DiagnosisResult,
    compare_same_call_matrix_terms,
    compare_thermal_families,
    diagnose_rate7_cj2_records,
)
from .msolvelucy_final_snapshot import (
    MSolveLucyFinalSnapshotParityResult,
    compare_msolvelucy_final_snapshot,
)

from .leveltemp_energy_parity import (
    LeveltempEnergyParityResult,
    compare_leveltemp_energy_probe,
)

from .msolvelucy_initial_state import (
    MSolveLucyInitialStateError,
    MSolveLucyInitialPopulationReference,
    MSolveLucyInitialPopulationParityResult,
    load_msolvelucy_initial_population_reference,
    compare_msolvelucy_initial_population,
    compare_msolvelucy_initial_populations,
)

from .calc_hmc_all_parity import (
    CalcHMCAllParityError,
    CalcHMCAllProbeCritfReference,
    CalcHMCAllProbeElementReference,
    CalcHMCAllParityRow,
    CalcHMCAllPreContinuumParityResult,
    load_calc_hmc_all_probe_critf,
    load_calc_hmc_all_probe_element_reference,
    compare_calc_hmc_all_pre_continuum_probe,
    write_calc_hmc_all_pre_continuum_parity_products,
)

from .population_parity import (
    PopulationParityError,
    XSTARPopulationReference,
    XSTARRuntimeContextReference,
    PopulationMetrics,
    ElementPopulationParityResult,
    load_xstar_population_reference,
    load_xstar_runtime_context_reference,
    compare_element_population_parity,
    write_element_population_parity_products,
)

from .msolvelucy_state_parity import (
    MSolveStateParityError,
    StateComponentMetrics,
    MSolveStateParityResult,
    compare_msolvelucy_state_probe,
    write_msolvelucy_state_parity_products,
)

from .full_element_matrix_parity import (
    FullElementMatrixParityError,
    MatrixFamilyParityMetrics,
    FullElementMatrixParityResult,
    compare_full_element_matrix_probe,
    write_full_element_matrix_parity_products,
)

from .ucalc_dispatch import (
    UCalcBranch,
    UCalcDispatcher,
    default_ucalc_dispatcher,
)

from .v0434_regression import (
    V0434_BASELINE_TARGET_COUNTS,
    V0434RegressionGateResult,
    assess_v0434_oxygen_correction_gates,
    write_v0434_regression_gate_summary,
)


__all__ = [
    "FortranSourceFile",
    "FortranRoutine",
    "XSTARSourceInventory",
    "build_source_inventory",
    "write_source_inventory",
    "PORT_LEDGER_VERSION",
    "COMPLETED_SOURCE_PORT_MILESTONES",
    "NEXT_COHERENT_SOURCE_PORT_TARGET",
    "PortStatus",
    "PortLedgerEntry",
    "XSTARPortLedger",
    "default_port_ledger",
    "FortranArray",
    "FortranRuntimeError",
    "fortran_nint",
    "fortran_sign",
    "fortran_mod",
    "XSTARAtomicState",
    "XSTARPlasmaState",
    "XSTARRadiationState",
    "XSTARMatrixState",
    "XSTARThermalState",
    "XSTARLocalZoneState",
    "XSTARTransferState",
    "XSTARPythonState",
    "XSTARSourceRoutine",
    "XSTARCALC_SOURCE_ORDER",
    "XSTARCALC_FIXED_STATE_ORDER",
    "ZONE_SOURCE_ORDER",
    "XSTARStage",
    "UnportedXSTARSourceRoutine",
    "UnportedXSTARRoutine",
    "XSTARPythonDriver",
    "UCalcLevel",
    "UCalcLevelTable",
    "UCalcRecord",
    "UCalcContext",
    "UCalcStatus",
    "UCalcProvenance",
    "UCalcResult",
    "UCalcExecutionError",
    "UCalcUntranslatedBranch",
    "UCalcBranchSpec",
    "SourceFaithfulUCalc",
    "complete_ucalc_branch_catalog",
    "default_source_faithful_ucalc",
    "build_ucalc_data_type_inventory",
    "build_ucalc_branch_catalog_rows",
    "build_ucalc_index_only_samples",
    "write_ucalc_subsystem_products",
    "UCalcBranch",
    "UCalcDispatcher",
    "default_ucalc_dispatcher",
    "AtomicDatabaseError",
    "PackedRecordHeader",
    "FortranPackedVector",
    "FortranPointerTable",
    "XSTARMasterData",
    "XSTARDerivedPointers",
    "AtomicDatabaseBuildResult",
    "DBWK2Instruction",
    "DBWK2Result",
    "readtbl",
    "setptrs",
    "dbwk2",
    "populate_atomic_state",
    "load_atomic_database_state",
    "register_atomic_database_stages",
    "POINTER_CACHE_FORMAT_VERSION",
    "atomic_database_fingerprint",
    "save_derived_pointer_cache",
    "load_derived_pointer_cache",
    "write_atomic_database_products",
    "XSTARLinearAlgebraError",
    "LUDecomposition",
    "LinearSolveResult",
    "ludcmp",
    "lubksb",
    "mprove",
    "leqt2f",
    "ElementEquilibriumError",
    "ElementIonBlock",
    "ElementBasisRow",
    "ElementCompactBasis",
    "EscapeProbabilityContext",
    "ElementEquilibriumContext",
    "MatrixTerm",
    "IonAssemblySummary",
    "ElementMatrixAssembly",
    "LucyIterationTrace",
    "LucySolveResult",
    "ElementEquilibriumResult",
    "pescl",
    "pescv",
    "build_level_table",
    "build_element_compact_basis",
    "levwk",
    "levwkelement",
    "assemble_element_matrix",
    "msolvelucy",
    "solve_element_statistical_equilibrium",
    "register_element_equilibrium_stage",
    "write_element_equilibrium_products",
    "IonBalanceError",
    "CalcIonRatesContext",
    "CalcIonRateContribution",
    "CalcIonRatesResult",
    "IoneqmResult",
    "IstrucResult",
    "IonStageLimitResult",
    "calc_ion_rates",
    "ioneqm",
    "istruc",
    "select_ion_stage_limits",
    "calc_element_pre_matrix_balance",
    "ElementXSTARVectorClosure",
    "XSTARVectorMatrixClosureResult",
    "build_xstar_vector_matrix_closure",
    "SameCallMatrixParityResult",
    "ThermalFamilyParityResult",
    "Rate7CJ2DiagnosisResult",
    "compare_same_call_matrix_terms",
    "compare_thermal_families",
    "diagnose_rate7_cj2_records",
    "MSolveLucyFinalSnapshotParityResult",
    "compare_msolvelucy_final_snapshot",
    "LeveltempEnergyParityResult",
    "compare_leveltemp_energy_probe",
    "MSolveLucyInitialStateError",
    "MSolveLucyInitialPopulationReference",
    "MSolveLucyInitialPopulationParityResult",
    "load_msolvelucy_initial_population_reference",
    "compare_msolvelucy_initial_population",
    "compare_msolvelucy_initial_populations",
    "CalcHMCAllError",
    "FixedStateElementRequest",
    "FixedStateContinuumResult",
    "FixedStateElementResult",
    "FixedStateCalcHMCAllResult",
    "resolve_calc_hmc_all_density",
    "calc_hmc_all",
    "register_fixed_state_calc_hmc_all",
    "write_fixed_state_calc_hmc_all_products",
    "AllElementFixedStateError",
    "OxygenCall73RegressionGate",
    "OXYGEN_CALL73_REQUIRED_TRUE_FIELDS",
    "validate_oxygen_call73_regression",
    "AllElementProbeElement",
    "AllElementFixedStatePlan",
    "AllElementFixedStateRun",
    "load_all_element_fixed_state_plan",
    "build_all_element_fixed_state_requests",
    "run_all_element_fixed_state",
    "write_all_element_fixed_state_products",
    "CalcHMCAllParityError",
    "CalcHMCAllProbeCritfReference",
    "CalcHMCAllProbeElementReference",
    "CalcHMCAllParityRow",
    "CalcHMCAllPreContinuumParityResult",
    "load_calc_hmc_all_probe_critf",
    "load_calc_hmc_all_probe_element_reference",
    "compare_calc_hmc_all_pre_continuum_probe",
    "write_calc_hmc_all_pre_continuum_parity_products",
    "PopulationParityError",
    "XSTARPopulationReference",
    "XSTARRuntimeContextReference",
    "PopulationMetrics",
    "ElementPopulationParityResult",
    "load_xstar_population_reference",
    "load_xstar_runtime_context_reference",
    "compare_element_population_parity",
    "write_element_population_parity_products",
    "MSolveStateParityError",
    "StateComponentMetrics",
    "MSolveStateParityResult",
    "compare_msolvelucy_state_probe",
    "write_msolvelucy_state_parity_products",
    "FullElementMatrixParityError",
    "MatrixFamilyParityMetrics",
    "FullElementMatrixParityResult",
    "compare_full_element_matrix_probe",
    "write_full_element_matrix_parity_products",
    "V0434_BASELINE_TARGET_COUNTS",
    "V0434RegressionGateResult",
    "assess_v0434_oxygen_correction_gates",
    "write_v0434_regression_gate_summary",
    "EscapeStateError",
    "EscapeStateBuildResult",
    "load_escape_state_from_xstar_run",
    "write_escape_state_npz",
    "write_escape_state_summary",
]
