"""Source-faithful element statistical-equilibrium subsystem.

This module translates the execution sequence

``levwkelement -> calc_hmc_ion -> calc_hmc_element -> msolvelucy``

as one coherent Python subsystem.  It preserves XSTAR's one-based compact
``ipmat2`` topology, including the shared identity between an ion's continuum
row and the next ion's ground row, traverses records through the pointer tables
built by :mod:`xstar_atomic.source_port.atomic_database`, inserts the four
matrix rows emitted by ``calc_hmc_ion.f90``, and solves populations with the
Lucy superlevel iteration from ``msolvelucy.f90``.

The implementation is deliberately array-oriented and source named.  It does
not use historical probe matrices or fitted source terms.  A record that lacks
required plasma, level, escape, or radiation context is reported explicitly
and prevents the strict direct-solve readiness gate.
"""
from __future__ import annotations

from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Any, Dict, Iterable, Iterator, List, Mapping, MutableMapping, Optional, Sequence, Tuple
import csv
import json
import math

import numpy as np

from .atomic_database import XSTARMasterData, XSTARDerivedPointers
from .linear_algebra import XSTARLinearAlgebraError, leqt2f
from .ucalc import (
    SourceFaithfulUCalc,
    UCalcContext,
    UCalcLevel,
    UCalcLevelTable,
    UCalcResult,
    UCalcStatus,
    default_source_faithful_ucalc,
)


class ElementEquilibriumError(RuntimeError):
    """Raised when a source-faithful element matrix cannot be constructed."""


@dataclass(frozen=True)
class ElementIonBlock:
    """One ion block in the compact ``ipmat2`` element basis."""

    ion_index: int
    ion_record: int
    element_z: int
    ion_stage: int
    nlev: int
    compact_start: int
    compact_stop: int
    first_level_record: int
    label: str = ""

    def compact_index(self, local_level: int) -> int:
        return self.compact_start + int(local_level) - 1


@dataclass
class ElementBasisRow:
    """One compact population unknown with all physical alias roles."""

    compact_index: int
    superlevel: int = 0
    ion_counter: int = 0
    roles: List[Dict[str, Any]] = field(default_factory=list)

    @property
    def is_shared_alias(self) -> bool:
        return len(self.roles) > 1


@dataclass
class ElementCompactBasis:
    """Exact compact element basis generated by ``calc_hmc_element`` rules."""

    element_z: int
    min_ion_stage: int
    max_ion_stage: int
    blocks: List[ElementIonBlock]
    rows: List[ElementBasisRow]
    n_rows: int
    n_superlevels: int
    n_ions: int
    normalization_row: int
    role_to_row: Dict[Tuple[int, int], int] = field(default_factory=dict)

    def row(self, compact_index: int) -> ElementBasisRow:
        if compact_index < 1 or compact_index > self.n_rows:
            raise IndexError(f"compact row {compact_index} outside 1..{self.n_rows}")
        return self.rows[compact_index - 1]

    def endpoint_row(self, ion_index: int, local_endpoint: int) -> int:
        block = next((b for b in self.blocks if b.ion_index == int(ion_index)), None)
        if block is None:
            raise KeyError(f"ion index {ion_index} is not in the compact basis")
        row = block.compact_index(local_endpoint)
        if row < 1 or row > self.n_rows:
            raise IndexError(
                f"ion {ion_index} local endpoint {local_endpoint} maps to compact row {row}, "
                f"outside 1..{self.n_rows}"
            )
        return row

    @property
    def nsup(self) -> np.ndarray:
        out = np.zeros(self.n_rows + 1, dtype=np.int32)
        for row in self.rows:
            out[row.compact_index] = row.superlevel
        return out

    @property
    def nion(self) -> np.ndarray:
        """One-based compact ion-block counters used internally by ``msolvelucy``."""
        out = np.zeros(self.n_rows + 1, dtype=np.int32)
        for row in self.rows:
            out[row.compact_index] = row.ion_counter
        return out

    @property
    def ion_stage(self) -> np.ndarray:
        """Physical ion stage for each compact row, matching XSTAR probe ``nion``.

        ``calc_hmc_element`` overwrites a shared parent-continuum/next-ground
        compact row when the following ion block is installed.  Therefore a
        shared alias takes the ion stage of its next-ion ground role, i.e. the
        largest physical ion stage among its roles.  This is distinct from the
        compact block counter returned by :attr:`nion`.
        """
        out = np.zeros(self.n_rows + 1, dtype=np.int32)
        for row in self.rows:
            stages = [int(role.get("ion_stage", 0)) for role in row.roles if int(role.get("ion_stage", 0)) > 0]
            if stages:
                out[row.compact_index] = max(stages)
            elif row.ion_counter > 0:
                out[row.compact_index] = self.min_ion_stage + row.ion_counter - 1
        return out


@dataclass(frozen=True)
class EscapeProbabilityContext:
    """Line/RRC optical-depth state used by ``calc_hmc_ion``.

    Arrays are one-based conceptually but are passed as ordinary zero-based
    NumPy sequences.  Missing entries are treated as optically thin only when
    ``allow_missing_as_zero`` is true; otherwise the affected record is
    reported as context blocked.
    """

    line_tau_in: Optional[np.ndarray] = None
    line_tau_out: Optional[np.ndarray] = None
    continuum_tau_in: Optional[np.ndarray] = None
    continuum_tau_out: Optional[np.ndarray] = None
    allow_missing_as_zero: bool = False

    @staticmethod
    def _value(values: Optional[np.ndarray], index: int) -> Optional[float]:
        if values is None or index <= 0 or index > len(values):
            return None
        value = float(values[index - 1])
        return value if math.isfinite(value) else None

    def line_taus(self, index: int) -> Tuple[Optional[float], Optional[float]]:
        return self._value(self.line_tau_in, index), self._value(self.line_tau_out, index)

    def continuum_taus(self, index: int) -> Tuple[Optional[float], Optional[float]]:
        return self._value(self.continuum_tau_in, index), self._value(self.continuum_tau_out, index)


@dataclass
class ElementEquilibriumContext:
    """Runtime state required by the translated element subsystem."""

    temperature_k: float
    hydrogen_density_cm3: float
    electron_fraction_xee: float
    min_ion_stage: int
    max_ion_stage: int
    radiation: Any = None
    escape: EscapeProbabilityContext = field(default_factory=EscapeProbabilityContext)
    covering_fraction: float = 1.0
    turbulent_velocity_km_s: float = 0.0
    neutral_h_density_cm3: float = 0.0
    ionized_h_density_cm3: float = 0.0
    abundance: float = 1.0
    lfast: int = 2
    initial_populations: Optional[np.ndarray] = None
    strict_context: bool = True
    max_lucy_iterations: int = 200
    max_fixed_point_iterations: int = 200
    lucy_tolerance: float = 1.0e-2
    fixed_point_tolerance: float = 1.0e-2
    allow_lstsq_fallback: bool = True
    capture_lucy_trace: bool = False

    @property
    def electron_density_cm3(self) -> float:
        return self.hydrogen_density_cm3 * self.electron_fraction_xee


@dataclass(frozen=True)
class MatrixTerm:
    """One source-level ``ajisb/cjisb/indb`` entry."""

    term_index: int
    record: int
    data_type: int
    rate_type: int
    ion_index: int
    ion_stage: int
    role: str
    row: int
    column: int
    aj1: float
    aj2: float
    cj: float
    cj2: float
    idest1: int
    idest2: int
    lower_endpoint: int
    upper_endpoint: int
    ucalc_status: str
    source_row_unclamped: int = 0
    source_column_unclamped: int = 0
    source_ipmat_clamped: bool = False


@dataclass
class IonAssemblySummary:
    ion_index: int
    ion_stage: int
    ion_record: int
    nlev: int
    n_records_seen: int = 0
    n_records_evaluated: int = 0
    n_records_source_noop: int = 0
    n_records_skipped_by_calc_hmc_ion: int = 0
    n_records_blocked: int = 0
    n_records_invalid_endpoint: int = 0
    n_matrix_terms: int = 0
    blocked_reasons: Dict[str, int] = field(default_factory=dict)


@dataclass
class ElementMatrixAssembly:
    """Output of ``calc_hmc_ion/calc_hmc_element`` translation."""

    basis: ElementCompactBasis
    initial_populations: np.ndarray
    terms: List[MatrixTerm]
    dense_matrix: np.ndarray
    normalized_matrix: np.ndarray
    rhs: np.ndarray
    heating_matrix: np.ndarray
    heating_matrix2: np.ndarray
    ion_summaries: List[IonAssemblySummary]
    blocked_records: List[Dict[str, Any]]
    record_results: List[Dict[str, Any]]
    n_records_seen: int
    n_records_evaluated: int
    n_records_source_noop: int
    n_records_skipped: int
    n_records_blocked: int
    n_unmapped_endpoints: int
    strict_assembly_ready: bool
    n_source_ipmat_endpoint_clamps: int = 0


@dataclass
class LucyIterationTrace:
    """Long-form state captured from the translated ``msolvelucy`` loops."""

    outer_level_rows: List[Dict[str, Any]] = field(default_factory=list)
    superlevel_rows: List[Dict[str, Any]] = field(default_factory=list)
    condensed_matrix_rows: List[Dict[str, Any]] = field(default_factory=list)
    fixed_point_rows: List[Dict[str, Any]] = field(default_factory=list)


@dataclass
class LucySolveResult:
    """Result and diagnostics from the translated ``msolvelucy`` solver."""

    populations: np.ndarray
    converged: bool
    outer_iterations: int
    fixed_point_iterations: int
    final_outer_difference: float
    final_fixed_point_difference: float
    n_negative_populations: int
    normalization: float
    normalization_error: float
    max_relative_row_residual: float
    max_active_relative_row_residual: float
    l1_row_residual: float
    l1_relative_row_residual: float
    n_zero_scale_rows: int
    row_residual: np.ndarray
    row_scale: np.ndarray
    relative_row_residual: np.ndarray
    solver_method: str
    condensed_rank: int
    condensed_dimension: int
    dense_rank: int
    dense_condition_number: float
    heating: float
    cooling: float
    heating2: float
    cooling2: float
    gamma: np.ndarray
    alpha: np.ndarray
    fgamma: np.ndarray
    falpha: np.ndarray
    igammamax_record: np.ndarray
    ialphamax_record: np.ndarray
    ion_population_totals: np.ndarray
    ionization_totals: np.ndarray
    recombination_totals: np.ndarray
    ionization_components: np.ndarray
    recombination_components: np.ndarray
    notes: List[str] = field(default_factory=list)
    trace: Optional[LucyIterationTrace] = None


@dataclass
class ElementEquilibriumResult:
    """Whole ``levwkelement -> msolvelucy`` subsystem result."""

    assembly: ElementMatrixAssembly
    solve: Optional[LucySolveResult]
    full_element_direct_solve_ready: bool
    source_sequence_complete: bool = True
    population_parity: Optional[Any] = None
    msolvelucy_state_parity: Optional[Any] = None
    full_element_matrix_parity: Optional[Any] = None


# ---------------------------------------------------------------------------
# Source helpers


def pescl(tau: float) -> float:
    """Translate ``pescl.f90`` line escape probability."""
    tau = float(tau)
    tauw = 1.0e5
    if tau < 1.0:
        if tau < 1.0e-5:
            value = 1.0
        else:
            aa = 2.0 * tau
            value = (1.0 - math.exp(-aa)) / aa
    else:
        bb = 0.5 * math.sqrt(max(math.log(tau), 0.0)) / (1.0 + tau / tauw)
        value = 1.0 / (tau * math.sqrt(math.pi) * (1.2 + bb))
    return value / 2.0


def pescv(tau: float) -> float:
    """Translate ``pescv.f90`` RRC escape probability."""
    return max(math.exp(-float(tau)), 1.0e-12) / 2.0


def _iter_ion_records(derived: XSTARDerivedPointers, element_z: int) -> Iterator[Tuple[int, int, int]]:
    for ion_index in range(1, derived.n_ions + 1):
        if int(derived.ion_element_z[ion_index]) == int(element_z):
            yield ion_index, int(derived.ion_stage[ion_index]), int(derived.ion_records[ion_index])


def _record_label(master: XSTARMasterData, record: int) -> str:
    try:
        return master.record_chars(record).decode("latin-1", errors="replace").strip("\x00 ")
    except Exception:
        return ""


def build_level_table(
    master: XSTARMasterData,
    derived: XSTARDerivedPointers,
    ion_index: int,
) -> UCalcLevelTable:
    """Translate ``calc_rates_level_lte`` record unpacking for one ion."""
    nlev = int(derived.nlevs[ion_index])
    ion_record = int(derived.ion_records[ion_index])
    levels: Dict[int, UCalcLevel] = {}
    rec = int(derived.npfi[13, ion_index])
    while rec and int(derived.npar[rec]) == ion_record:
        header = master.header(rec)
        if header.rate_type == 13:
            reals = master.record_reals(rec)
            ints = master.record_integers(rec)
            if len(ints) >= 2:
                local = int(ints[-2])
                if 1 <= local <= nlev:
                    energy = float(reals[0]) if len(reals) > 0 else 0.0
                    weight = float(reals[1]) if len(reals) > 1 else 0.0
                    ionpot = float(reals[3]) if len(reals) > 3 else energy
                    levels[local] = UCalcLevel(
                        index=local,
                        energy_ev=energy,
                        statistical_weight=weight,
                        ionization_potential_ev=ionpot,
                        continuum_energy_ev=energy,
                        principal_n=int(ints[0]) if len(ints) > 0 else None,
                        orbital_l=int(ints[2]) if len(ints) > 2 else None,
                        label=_record_label(master, rec),
                    )
        rec = int(derived.npnxt[rec]) if rec else 0
    missing = [i for i in range(1, nlev + 1) if i not in levels]
    if missing:
        raise ElementEquilibriumError(
            f"ion index {ion_index} is missing level records {missing[:8]}"
            + ("..." if len(missing) > 8 else "")
        )
    return UCalcLevelTable(levels=levels, nlev=nlev)


def build_element_compact_basis(
    master: XSTARMasterData,
    derived: XSTARDerivedPointers,
    *,
    element_z: int,
    min_ion_stage: int,
    max_ion_stage: int,
) -> ElementCompactBasis:
    """Translate the compact ``ipmat/ipmat2/nsup/nion`` basis construction."""
    selected = [
        (idx, stage, rec)
        for idx, stage, rec in _iter_ion_records(derived, element_z)
        if min_ion_stage <= stage <= max_ion_stage
    ]
    selected.sort(key=lambda x: x[1])
    if not selected:
        raise ElementEquilibriumError(
            f"no ions for Z={element_z} in stage range {min_ion_stage}..{max_ion_stage}"
        )

    blocks: List[ElementIonBlock] = []
    rows_by_index: Dict[int, ElementBasisRow] = {}
    role_to_row: Dict[Tuple[int, int], int] = {}
    ipmat2 = 0
    nsp = 1
    nionp = 0

    for ion_index, stage, ion_record in selected:
        nionp += 1
        nlev = int(derived.nlevs[ion_index])
        if nlev <= 0:
            raise ElementEquilibriumError(f"ion index {ion_index} has invalid nlev={nlev}")
        start = ipmat2 + 1
        stop = ipmat2 + nlev
        block = ElementIonBlock(
            ion_index=ion_index,
            ion_record=ion_record,
            element_z=element_z,
            ion_stage=stage,
            nlev=nlev,
            compact_start=start,
            compact_stop=stop,
            first_level_record=int(derived.npfi[13, ion_index]),
            label=_record_label(master, ion_record),
        )
        blocks.append(block)

        # Ground row.  If shared with the previous ion continuum, the newer
        # spectroscopic-ground role determines nsup/nion exactly as in Fortran.
        ground = rows_by_index.setdefault(start, ElementBasisRow(start))
        ground.superlevel = nsp
        ground.ion_counter = nionp

        if nlev > 2:
            nsp += 1
            for local in range(2, nlev):
                row_index = start + local - 1
                row = rows_by_index.setdefault(row_index, ElementBasisRow(row_index))
                row.superlevel = nsp
                row.ion_counter = nionp
        nsp += 1

        for local in range(1, nlev + 1):
            row_index = start + local - 1
            row = rows_by_index.setdefault(row_index, ElementBasisRow(row_index))
            role = {
                "ion_index": ion_index,
                "ion_stage": stage,
                "local_level": local,
                "role": (
                    "ground"
                    if local == 1
                    else "parent_continuum_or_next_ground"
                    if local == nlev
                    else "spectroscopic_or_superlevel"
                ),
                "ion_record": ion_record,
            }
            row.roles.append(role)
            role_to_row[(ion_index, local)] = row_index

        ipmat2 += nlev - 1

    n_rows = ipmat2 + 1
    final_row = rows_by_index.setdefault(n_rows, ElementBasisRow(n_rows))
    final_row.superlevel = nsp
    final_row.ion_counter = nionp

    rows: List[ElementBasisRow] = []
    for index in range(1, n_rows + 1):
        row = rows_by_index.get(index)
        if row is None:
            raise ElementEquilibriumError(f"compact row {index} was not instantiated")
        if row.superlevel <= 0:
            # This can only be a final continuum role before its shared next-ion
            # ground role is seen; the final row is assigned above.
            row.superlevel = nsp
            row.ion_counter = nionp
        rows.append(row)

    return ElementCompactBasis(
        element_z=element_z,
        min_ion_stage=min_ion_stage,
        max_ion_stage=max_ion_stage,
        blocks=blocks,
        rows=rows,
        n_rows=n_rows,
        n_superlevels=nsp,
        n_ions=nionp,
        normalization_row=n_rows,
        role_to_row=role_to_row,
    )


def levwk(levels: UCalcLevelTable, context: ElementEquilibriumContext) -> np.ndarray:
    """Translate ``levwk.f90`` for one ion."""
    nlev = levels.nlev
    if nlev < 1:
        raise ElementEquilibriumError("levwk requires at least one level")
    tm = float(context.temperature_k)
    if tm <= 0:
        raise ElementEquilibriumError("temperature must be positive")
    xnx = float(context.electron_density_cm3)
    # bk/ergsev in XSTAR is 8.61707e-5 eV K^-1.
    bktm = 8.61707e-5 * tm
    q2 = 2.07e-16 * xnx * tm ** (-1.5)
    continuum = levels.require(nlev)
    emlt_cont = continuum.statistical_weight
    if emlt_cont <= 0:
        raise ElementEquilibriumError(f"continuum level {nlev} has non-positive statistical weight")
    rs = q2 / emlt_cont
    ethion = continuum.energy_ev
    rniss = np.zeros(nlev + 1, dtype=float)
    rniss[nlev] = 1.0
    bb = 1.0
    for local in range(1, nlev):
        level = levels.require(local)
        ethsht = max((ethion - level.energy_ev) / max(bktm, 1.0e-300), 0.0)
        explev2 = math.exp(max(-ethsht, -60.0))
        rniss[local] = level.statistical_weight / (explev2 / max(rs, 1.0e-300))
        bb += rniss[local]
    rniss[1:] /= max(bb, 1.0e-300)
    return rniss


def levwkelement(
    master: XSTARMasterData,
    derived: XSTARDerivedPointers,
    basis: ElementCompactBasis,
    context: ElementEquilibriumContext,
) -> Tuple[np.ndarray, Dict[int, UCalcLevelTable]]:
    """Translate ``levwkelement.f90`` and normalize the element seed."""
    rnise = np.zeros(basis.n_rows + 1, dtype=float)
    level_tables: Dict[int, UCalcLevelTable] = {}
    ipmatsv = 0
    last_rnisi: Optional[np.ndarray] = None
    last_nlev = 0

    for block in basis.blocks:
        levels = build_level_table(master, derived, block.ion_index)
        level_tables[block.ion_index] = levels
        rnisi = levwk(levels, context)
        last_rnisi = rnisi
        last_nlev = block.nlev
        if block.ion_stage == basis.min_ion_stage:
            rnise[1 + ipmatsv] = rnisi[1]
        for local in range(2, block.nlev + 1):
            target = local + ipmatsv
            if block.ion_stage > basis.min_ion_stage:
                rnise[target] = min(
                    1.0e66,
                    rnise[target - 1] * rnisi[local] / (1.0e-37 + rnisi[local - 1]),
                )
            else:
                rnise[target] = rnisi[local]
        ipmatsv += block.nlev - 1

    if last_rnisi is None or last_nlev < 2:
        raise ElementEquilibriumError("cannot construct fully stripped element population")
    rnise[ipmatsv + 1] = (
        rnise[ipmatsv] * last_rnisi[last_nlev] / (1.0e-97 + last_rnisi[last_nlev - 1])
    )
    total = float(np.sum(rnise[1 : basis.n_rows + 1]))
    if total <= 0 or not math.isfinite(total):
        raise ElementEquilibriumError("levwkelement produced a non-positive normalization")
    rnise[1 : basis.n_rows + 1] /= total
    return rnise, level_tables


def _escape_factors(
    record: int,
    rate_type: int,
    derived: XSTARDerivedPointers,
    context: ElementEquilibriumContext,
) -> Tuple[float, float, Optional[str]]:
    ptmp1 = 0.5
    ptmp2 = 0.5
    if rate_type == 4:
        index = int(derived.nplini[record]) if record < len(derived.nplini) else 0
        tau1, tau2 = context.escape.line_taus(index)
        if tau1 is None or tau2 is None:
            if context.escape.allow_missing_as_zero:
                tau1 = tau2 = 0.0
            else:
                return ptmp1, ptmp2, f"missing_line_optical_depth_for_line_index_{index}"
        ptmp1 = pescl(tau1) * (1.0 - context.covering_fraction)
        ptmp2 = (
            pescl(tau2) * (1.0 - context.covering_fraction)
            + 2.0 * pescl(tau1 + tau2) * context.covering_fraction
        )
    elif rate_type == 7:
        index = int(derived.npconi2[record]) if record < len(derived.npconi2) else 0
        tau1, tau2 = context.escape.continuum_taus(index)
        if tau1 is None or tau2 is None:
            if context.escape.allow_missing_as_zero:
                tau1 = tau2 = 0.0
            else:
                return ptmp1, ptmp2, f"missing_continuum_optical_depth_for_index_{index}"
        ptmp1 = pescv(tau1) * (1.0 - context.covering_fraction)
        ptmp2 = (
            pescv(tau2) * (1.0 - context.covering_fraction)
            + 2.0 * pescv(tau1 + tau2) * context.covering_fraction
        )
    return ptmp1, ptmp2, None


def _endpoint_energy(levels: UCalcLevelTable, endpoint: int) -> Optional[float]:
    level = levels.get(endpoint)
    return None if level is None else float(level.energy_ev)


def _lower_upper(result: UCalcResult, levels: UCalcLevelTable) -> Tuple[int, int]:
    id1, id2 = int(result.idest1), int(result.idest2)
    lower, upper = id1, id2
    if id1 <= 0 or id2 <= 0:
        return lower, upper
    if result.rate_type not in {7, 41}:
        e1 = _endpoint_energy(levels, id1)
        e2 = _endpoint_energy(levels, id2)
        if e1 is not None and e2 is not None:
            if (e1 / (1.0e-24 + e2) - 1.0) < 1.0e-8:
                upper, lower = id2, id1
            else:
                upper, lower = id1, id2
    return lower, upper


def _matrix_terms_for_result(
    *,
    result: UCalcResult,
    basis: ElementCompactBasis,
    block: ElementIonBlock,
    levels: UCalcLevelTable,
    term_start: int,
    xpx: float,
) -> List[MatrixTerm]:
    lower, upper = _lower_upper(result, levels)
    if lower <= 0 or upper <= 0:
        raise ElementEquilibriumError(
            f"record {result.record} returned invalid endpoints {result.idest1},{result.idest2}"
        )
    raw_row_lower = block.compact_index(lower)
    raw_row_upper = block.compact_index(upper)
    if raw_row_lower <= 0 or raw_row_upper <= 0:
        raise ElementEquilibriumError(
            f"record {result.record} endpoints {lower},{upper} map to non-positive rows "
            f"{raw_row_lower},{raw_row_upper}"
        )

    # msolvelucy.f90 aliases endpoints beyond the active compact dimension
    # through ``min(ipmat, indb(...))``. Preserve that source behavior rather
    # than rejecting excited-parent destinations outside the selected basis.
    row_lower = min(basis.n_rows, raw_row_lower)
    row_upper = min(basis.n_rows, raw_row_upper)

    a1, a2 = float(result.ans1), float(result.ans2)
    specs = (
        ("forward_offdiag", row_upper, row_lower, raw_row_upper, raw_row_lower, a1, a2, 0.0, 0.0),
        ("reverse_offdiag", row_lower, row_upper, raw_row_lower, raw_row_upper, a2, a1, 0.0, 0.0),
        ("forward_diag_loss", row_lower, row_lower, raw_row_lower, raw_row_lower, -a1, -a1, float(result.ans4) * xpx, float(result.ans6) * xpx),
        ("reverse_diag_loss", row_upper, row_upper, raw_row_upper, raw_row_upper, -a2, -a2, -float(result.ans3) * xpx, -float(result.ans5) * xpx),
    )
    out: List[MatrixTerm] = []
    for offset, (role, row, col, raw_row, raw_col, aj1, aj2, cj, cj2) in enumerate(specs):
        out.append(
            MatrixTerm(
                term_index=term_start + offset,
                record=result.record,
                data_type=result.data_type,
                rate_type=result.rate_type,
                ion_index=block.ion_index,
                ion_stage=block.ion_stage,
                role=role,
                row=row,
                column=col,
                aj1=aj1,
                aj2=aj2,
                cj=cj,
                cj2=cj2,
                idest1=result.idest1,
                idest2=result.idest2,
                lower_endpoint=lower,
                upper_endpoint=upper,
                ucalc_status=result.status.value,
                source_row_unclamped=raw_row,
                source_column_unclamped=raw_col,
                source_ipmat_clamped=(raw_row != row or raw_col != col),
            )
        )
    return out


def assemble_element_matrix(
    master: XSTARMasterData,
    derived: XSTARDerivedPointers,
    *,
    element_z: int,
    context: ElementEquilibriumContext,
    dispatcher: Optional[SourceFaithfulUCalc] = None,
) -> ElementMatrixAssembly:
    """Translate ``calc_hmc_ion`` and ``calc_hmc_element`` matrix assembly."""
    dispatcher = dispatcher or default_source_faithful_ucalc()
    basis = build_element_compact_basis(
        master,
        derived,
        element_z=element_z,
        min_ion_stage=context.min_ion_stage,
        max_ion_stage=context.max_ion_stage,
    )
    rnise, level_tables = levwkelement(master, derived, basis, context)
    if context.initial_populations is not None:
        supplied = np.asarray(context.initial_populations, dtype=float).reshape(-1)
        if supplied.size not in {basis.n_rows, basis.n_rows + 1}:
            raise ElementEquilibriumError(
                f"initial population length {supplied.size} does not match {basis.n_rows}"
            )
        rnise = np.zeros(basis.n_rows + 1, dtype=float)
        rnise[1:] = supplied[-basis.n_rows :]
        total = rnise[1:].sum()
        if total <= 0:
            raise ElementEquilibriumError("supplied initial populations have non-positive sum")
        rnise[1:] /= total

    # XSTAR addresses excited parent-ion destinations in the current ion-local
    # endpoint space as ``nlevp + parent_local_level - 1``.  Build those maps
    # once from the adjacent selected ion so the unified ucalc dispatcher can
    # use the same parent excitation energies and statistical weights as the
    # source.  The shared parent-ground/current-continuum endpoint remains in
    # the current level table and therefore does not require an override.
    parent_destination_context: Dict[int, Tuple[Dict[int, float], Dict[int, float]]] = {}
    for block_index, block in enumerate(basis.blocks):
        energy_by_destination: Dict[int, float] = {}
        weight_by_destination: Dict[int, float] = {}
        if block_index + 1 < len(basis.blocks):
            parent_block = basis.blocks[block_index + 1]
            parent_levels = level_tables[parent_block.ion_index]
            for parent_local in range(2, parent_levels.nlev + 1):
                destination = block.nlev + parent_local - 1
                parent_level = parent_levels.require(parent_local)
                energy_by_destination[destination] = float(parent_level.energy_ev)
                weight_by_destination[destination] = float(parent_level.statistical_weight)
        parent_destination_context[block.ion_index] = (
            energy_by_destination,
            weight_by_destination,
        )

    terms: List[MatrixTerm] = []
    blocked_records: List[Dict[str, Any]] = []
    record_results: List[Dict[str, Any]] = []
    ion_summaries: List[IonAssemblySummary] = []
    n_seen = n_eval = n_noop = n_skipped = n_blocked = n_unmapped = 0
    n_source_clamps = 0

    for block in basis.blocks:
            levels = level_tables[block.ion_index]
            parent_energy_map, parent_weight_map = parent_destination_context[block.ion_index]
            summary = IonAssemblySummary(
                ion_index=block.ion_index,
                ion_stage=block.ion_stage,
                ion_record=block.ion_record,
                nlev=block.nlev,
            )
            for data_type in range(1, derived.npfi.shape[0]):
                record = int(derived.npfi[data_type, block.ion_index])
                while record and int(derived.npar[record]) == block.ion_record:
                    header = master.header(record)
                    n_seen += 1
                    summary.n_records_seen += 1
                    # calc_hmc_ion source exclusions.
                    if (header.rate_type == 1 and header.data_type == 53) or header.rate_type in {8, 15}:
                        n_skipped += 1
                        summary.n_records_skipped_by_calc_hmc_ion += 1
                        record = int(derived.npnxt[record])
                        continue

                    ptmp1, ptmp2, escape_reason = _escape_factors(record, header.rate_type, derived, context)
                    ucontext = UCalcContext(
                        temperature_k=context.temperature_k,
                        hydrogen_density_cm3=context.hydrogen_density_cm3,
                        electron_fraction_xee=context.electron_fraction_xee,
                        neutral_h_density_cm3=context.neutral_h_density_cm3,
                        ionized_h_density_cm3=context.ionized_h_density_cm3,
                        turbulent_velocity_km_s=context.turbulent_velocity_km_s,
                        covering_fraction=context.covering_fraction,
                        ptmp1=ptmp1,
                        ptmp2=ptmp2,
                        # calc_hmc_ion calls ucalc with zero level
                        # abundances because this path assembles rates and
                        # heating/cooling but not opacity or emissivity.
                        abund1=0.0,
                        abund2=0.0,
                        jkion=block.ion_index,
                        nlev=block.nlev,
                        lfast=context.lfast,
                        levels=levels,
                        radiation=context.radiation,
                        derived_pointers=derived,
                        master=master,
                        extras={
                            "element_z": element_z,
                            "element_symbol": __import__("xstar_atomic.hierarchy", fromlist=["Z_TO_SYMBOL"]).Z_TO_SYMBOL.get(element_z, str(element_z)),
                            "ion_stage": block.ion_stage,
                            "ion_charge": block.ion_stage - 1,
                            "ion_record": block.ion_record,
                            "rnise": rnise,
                            "compact_start": block.compact_start,
                            "parent_level_energy_ev_by_destination": parent_energy_map,
                            "parent_level_stat_weight_by_destination": parent_weight_map,
                        },
                    )
                    if escape_reason is not None:
                        result = dispatcher.evaluate_record_number(
                            master,
                            record,
                            replace(ucontext, indonly=True),
                            parent_record=block.ion_record,
                            next_record=int(derived.npnxt[record]),
                            strict=False,
                        )
                        blocked = {
                            **result.to_dict(),
                            "status": UCalcStatus.CONTEXT_BLOCKED.value,
                            "reason": escape_reason,
                            "ion_index": block.ion_index,
                            "ion_stage": block.ion_stage,
                        }
                        blocked_records.append(blocked)
                        record_results.append(blocked)
                        n_blocked += 1
                        summary.n_records_blocked += 1
                        summary.blocked_reasons[escape_reason] = summary.blocked_reasons.get(escape_reason, 0) + 1
                        record = int(derived.npnxt[record])
                        continue

                    result = dispatcher.evaluate_record_number(
                        master,
                        record,
                        ucontext,
                        parent_record=block.ion_record,
                        next_record=int(derived.npnxt[record]),
                        strict=False,
                    )
                    row = result.to_dict()
                    row.update({"ion_index": block.ion_index, "ion_stage": block.ion_stage})
                    record_results.append(row)

                    if result.status is UCalcStatus.SOURCE_NOOP:
                        n_noop += 1
                        summary.n_records_source_noop += 1
                    elif result.status is not UCalcStatus.EVALUATED:
                        n_blocked += 1
                        summary.n_records_blocked += 1
                        reason = result.reason or result.status.value
                        summary.blocked_reasons[reason] = summary.blocked_reasons.get(reason, 0) + 1
                        blocked_records.append(row)
                    else:
                        # Source branches with a missing endpoint do not enter
                        # calc_hmc_ion's four-row matrix block.  They may still
                        # contribute scalar ionization/recombination totals.
                        if result.idest1 <= 0 or result.idest2 <= 0:
                            record_results[-1]["matrix_insertion_status"] = "source_nonmatrix_endpoint"
                            record = int(derived.npnxt[record])
                            continue
                        # Prevent duplicate rate-type-1 photoionization from excited levels.
                        if result.rate_type == 1 and result.idest1 != 1:
                            result = replace(result, ans1=0.0)
                        try:
                            new_terms = _matrix_terms_for_result(
                                result=result,
                                basis=basis,
                                block=block,
                                levels=levels,
                                term_start=len(terms) + 1,
                                xpx=context.hydrogen_density_cm3,
                            )
                        except (ElementEquilibriumError, IndexError) as exc:
                            n_unmapped += 1
                            summary.n_records_invalid_endpoint += 1
                            blocked = {**row, "reason": str(exc), "status": "invalid_endpoint"}
                            blocked_records.append(blocked)
                            if context.strict_context:
                                n_blocked += 1
                                summary.n_records_blocked += 1
                        else:
                            if any(term.source_ipmat_clamped for term in new_terms):
                                n_source_clamps += 1
                                record_results[-1]["source_ipmat_endpoint_clamped"] = True
                                record_results[-1]["source_ipmat_clamp_target_row"] = basis.n_rows
                            terms.extend(new_terms)
                            n_eval += 1
                            summary.n_records_evaluated += 1
                            summary.n_matrix_terms += len(new_terms)
                    record = int(derived.npnxt[record])
            ion_summaries.append(summary)

    dense = np.zeros((basis.n_rows, basis.n_rows), dtype=float)
    heat = np.zeros_like(dense)
    heat2 = np.zeros_like(dense)
    for term in terms:
        dense[term.row - 1, term.column - 1] += term.aj1
        heat[term.row - 1, term.column - 1] += term.cj
        heat2[term.row - 1, term.column - 1] += term.cj2

    normalized = dense.copy()
    rhs = np.zeros(basis.n_rows, dtype=float)
    normalized[basis.normalization_row - 1, :] = 1.0
    rhs[basis.normalization_row - 1] = 1.0

    strict_ready = n_blocked == 0 and n_unmapped == 0 and len(terms) > 0
    return ElementMatrixAssembly(
        basis=basis,
        initial_populations=rnise,
        terms=terms,
        dense_matrix=dense,
        normalized_matrix=normalized,
        rhs=rhs,
        heating_matrix=heat,
        heating_matrix2=heat2,
        ion_summaries=ion_summaries,
        blocked_records=blocked_records,
        record_results=record_results,
        n_records_seen=n_seen,
        n_records_evaluated=n_eval,
        n_records_source_noop=n_noop,
        n_records_skipped=n_skipped,
        n_records_blocked=n_blocked,
        n_unmapped_endpoints=n_unmapped,
        n_source_ipmat_endpoint_clamps=n_source_clamps,
        strict_assembly_ready=strict_ready,
    )


def _solve_normalized(matrix: np.ndarray, normalization_row: int, *, allow_lstsq: bool) -> Tuple[np.ndarray, str, int]:
    a = np.asarray(matrix, dtype=float).copy()
    n = a.shape[0]
    b = np.zeros(n, dtype=float)
    row = int(normalization_row) - 1
    a[row, :] = 1.0
    b[row] = 1.0
    rank = int(np.linalg.matrix_rank(a))
    try:
        solved = leqt2f(a, b)
        return solved.solution, solved.method, rank
    except (XSTARLinearAlgebraError, np.linalg.LinAlgError):
        if not allow_lstsq:
            raise
        x, *_ = np.linalg.lstsq(a, b, rcond=None)
        # Preserve leqt2f's population range treatment for the fallback.
        x = np.where(x < 1.0e-36, 0.0, x)
        x = np.where(x > 1.0e36, 1.0e36, x)
        return x, "numpy_lstsq_fallback", rank


def msolvelucy(
    assembly: ElementMatrixAssembly,
    context: ElementEquilibriumContext,
) -> LucySolveResult:
    """Translate ``msolvelucy.f90`` superlevel and fixed-point iteration."""
    basis = assembly.basis
    n = basis.n_rows
    x = np.asarray(assembly.initial_populations[1 : n + 1], dtype=float).copy()
    # Source ``msolvelucy.f90`` enters the first outer iteration with the
    # supplied population vector exactly as received.  It does not normalize
    # ``x`` until the fixed-point update.  Preserving the input scale is
    # essential for iteration-state parity with the captured pre-solve vector;
    # the condensed solve itself subsequently imposes number conservation.
    if not np.all(np.isfinite(x)) or float(np.sum(x)) <= 0.0:
        raise ElementEquilibriumError("msolvelucy received a non-positive or non-finite population seed")
    nsup = basis.nsup[1:]
    nion = basis.nion[1:]
    nspmx = basis.n_superlevels
    terms = assembly.terms
    eps = 1.0e-6
    eps2 = 1.0e-6
    outer_diff = 1.0
    fixed_diff = 0.0
    outer = 0
    total_fixed = 0
    solver_methods: List[str] = []
    runtime_notes: List[str] = []
    condensed_rank = 0
    used_dense_fallback = False
    trace = LucyIterationTrace() if context.capture_lucy_trace else None

    while outer_diff > context.lucy_tolerance and outer < context.max_lucy_iterations:
        outer += 1
        xo = x.copy()
        outer_start = x.copy()
        p = np.zeros(nspmx, dtype=float)
        for i in range(n):
            sp = int(nsup[i]) - 1
            if sp >= 0:
                p[sp] += x[i]
        rr = np.ones(n, dtype=float)
        for i in range(n):
            sp = int(nsup[i]) - 1
            if sp >= 0 and p[sp] > 1.0e-36:
                rr[i] = x[i] / (1.0e-48 + p[sp])

        condensed = np.zeros((nspmx, nspmx), dtype=float)
        for term in terms:
            mm = min(n, term.row) - 1
            nn = min(n, term.column) - 1
            spm = int(nsup[mm]) - 1
            spn = int(nsup[nn]) - 1
            if spm != spn and spm >= 0 and spn >= 0 and (abs(term.aj1) > 1.0e-48 or abs(term.aj2) > 1.0e-48):
                condensed[spm, spn] += term.aj1 * rr[nn]
                condensed[spm, spm] -= term.aj2 * rr[mm]

        p_start = p.copy()
        p_new, method, condensed_rank = _solve_normalized(
            condensed,
            nspmx,
            allow_lstsq=context.allow_lstsq_fallback,
        )
        solver_methods.append(method)
        for i in range(n):
            sp = int(nsup[i]) - 1
            x[i] = rr[i] * p_new[sp]
        x_after_condensed = x.copy()

        fixed_diff = 10.0
        fixed_iter = 0
        while fixed_iter < context.max_fixed_point_iterations and fixed_diff >= context.fixed_point_tolerance:
            fixed_iter += 1
            total_fixed += 1
            xold = x.copy()
            riu = np.zeros(n, dtype=float)
            rui = np.zeros(n, dtype=float)
            ril = np.zeros(n, dtype=float)
            rli = np.zeros(n, dtype=float)
            for term in terms:
                mm = term.row - 1
                nn = min(n, term.column) - 1
                if nn > mm:
                    riu[mm] += abs(term.aj2)
                    rui[mm] += abs(term.aj1) * x[nn]
                elif nn < mm:
                    ril[mm] += abs(term.aj2)
                    rli[mm] += abs(term.aj1) * x[nn]
            x = (rli + rui) / (ril + riu + 1.0e-24)
            total = float(np.sum(x))
            if not math.isfinite(total) or total <= 0:
                # Degenerate superlevel partitions can produce an all-zero
                # fixed-point update even when the full normalized linear
                # system is well posed.  Solve that same source matrix with
                # the translated leqt2f-equivalent normalization rather than
                # clipping or inventing populations.
                x, dense_method, _ = _solve_normalized(
                    assembly.dense_matrix,
                    basis.normalization_row,
                    allow_lstsq=context.allow_lstsq_fallback,
                )
                solver_methods.append("dense_" + dense_method)
                runtime_notes.append("Lucy fixed-point update was degenerate; used normalized full-matrix solve")
                used_dense_fallback = True
                fixed_diff = 0.0
                outer_diff = 0.0
                break
            x /= total
            mask = x > eps2
            if np.any(mask):
                ratios = np.ones(n, dtype=float)
                ratios[mask] = xold[mask] / x[mask]
                fixed_diff = float(np.sum((ratios[mask] - 1.0) ** 2))
            else:
                fixed_diff = 0.0
            if trace is not None:
                for i in range(n):
                    trace.fixed_point_rows.append(
                        {
                            "outer_iteration": outer,
                            "fixed_iteration": fixed_iter,
                            "global_fixed_iteration": total_fixed,
                            "compact_index": i + 1,
                            "superlevel": int(nsup[i]),
                            "ion_counter": int(nion[i]),
                            "population_before": float(xold[i]),
                            "riu": float(riu[i]),
                            "rui": float(rui[i]),
                            "ril": float(ril[i]),
                            "rli": float(rli[i]),
                            "population_after": float(x[i]),
                            "fixed_difference": float(fixed_diff),
                        }
                    )
            if fixed_diff >= 1.0e3:
                break

        if trace is not None:
            for i in range(n):
                trace.outer_level_rows.append(
                    {
                        "outer_iteration": outer,
                        "compact_index": i + 1,
                        "superlevel": int(nsup[i]),
                        "ion_counter": int(nion[i]),
                        "population_outer_start": float(outer_start[i]),
                        "rr": float(rr[i]),
                        "population_after_condensed": float(x_after_condensed[i]),
                        "population_after_fixed_point": float(x[i]),
                        "fixed_iterations_this_outer": fixed_iter,
                        "fixed_difference": float(fixed_diff),
                    }
                )
            for sp in range(nspmx):
                trace.superlevel_rows.append(
                    {
                        "outer_iteration": outer,
                        "superlevel": sp + 1,
                        "population_before_condensed_solve": float(p_start[sp]),
                        "population_after_condensed_solve": float(p_new[sp]),
                    }
                )
            for spm in range(nspmx):
                for spn in range(nspmx):
                    trace.condensed_matrix_rows.append(
                        {
                            "outer_iteration": outer,
                            "row_superlevel": spm + 1,
                            "column_superlevel": spn + 1,
                            "raw_matrix_value": float(condensed[spm, spn]),
                            "normalized_matrix_value": 1.0 if spm == nspmx - 1 else float(condensed[spm, spn]),
                        }
                    )

        if used_dense_fallback:
            break
        mask = x > eps
        if np.any(mask):
            denominator = xo[mask] + x[mask]
            frac = np.minimum(1.0e10, (xo[mask] - x[mask]) / np.where(denominator != 0.0, denominator, 1.0e-300))
            outer_diff = float(np.sum(frac**2))
        else:
            outer_diff = 0.0

    normalization = float(np.sum(x))
    residual = assembly.dense_matrix @ x
    raw_row_scale = np.sum(np.abs(assembly.dense_matrix) * np.abs(x[np.newaxis, :]), axis=1)
    row_scale = np.maximum(raw_row_scale, 1.0e-300)
    relative_residual = np.abs(residual) / row_scale
    active_residual_rows = raw_row_scale > 1.0e-12
    max_active_relative_residual = (
        float(np.max(relative_residual[active_residual_rows]))
        if np.any(active_residual_rows) else 0.0
    )
    l1_residual = float(np.sum(np.abs(residual)))
    l1_relative_residual = l1_residual / max(float(np.sum(raw_row_scale)), 1.0e-300)
    n_zero_scale_rows = int(np.count_nonzero(raw_row_scale <= 1.0e-300))

    heating = cooling = heating2 = cooling2 = 0.0
    for term in terms:
        if term.row == term.column:
            pop = x[term.row - 1]
            if term.cj > 0:
                cooling += pop * term.cj
            else:
                heating -= pop * term.cj
            if term.cj2 > 0:
                cooling2 += pop * term.cj2
            else:
                heating2 -= pop * term.cj2

    gamma = np.zeros(n, dtype=float)
    alpha = np.zeros(n, dtype=float)
    fgamma = np.zeros((5, n), dtype=float)
    falpha = np.zeros((5, n), dtype=float)
    gammamax = np.zeros(n, dtype=float)
    alphamax = np.zeros(n, dtype=float)
    igammamax = np.zeros(n, dtype=np.int64)
    ialphamax = np.zeros(n, dtype=np.int64)
    ion_population_totals = np.zeros(basis.n_ions, dtype=float)
    ionization_totals = np.zeros(basis.n_ions, dtype=float)
    recombination_totals = np.zeros(basis.n_ions, dtype=float)
    ionization_components = np.zeros((3, basis.n_ions), dtype=float)
    recombination_components = np.zeros((3, basis.n_ions), dtype=float)

    # msolvelucy excludes the final fully stripped continuum row when
    # accumulating xtot by ion.
    for i in range(max(0, n - 1)):
        ion_slot = int(nion[i]) - 1
        if 0 <= ion_slot < basis.n_ions:
            ion_population_totals[ion_slot] += x[i]

    rate_category = {3: 0, 4: 1, 5: 2, 7: 3}
    for term in terms:
        mm = min(n, term.row) - 1
        nn = min(n, term.column) - 1
        if mm != nn:
            out_rate = abs(term.aj2)
            in_rate = abs(term.aj1) * x[nn]
            gamma[mm] += out_rate
            alpha[mm] += in_rate
            if out_rate > gammamax[mm]:
                gammamax[mm] = out_rate
                igammamax[mm] = term.record
            if in_rate > alphamax[mm]:
                alphamax[mm] = in_rate
                ialphamax[mm] = term.record
            category = rate_category.get(term.rate_type)
            if category is not None:
                fgamma[category, mm] += out_rate
                falpha[category, mm] += in_rate

        # Source msolvelucy accumulates ionization/recombination only for
        # upward compact couplings of rate types 5 and 7.
        if term.row < term.column and term.rate_type in {5, 7}:
            ion_mm = int(nion[mm]) - 1
            ion_nn = int(nion[nn]) - 1
            if 0 <= ion_mm < basis.n_ions and ion_nn >= ion_mm:
                recomb = abs(term.aj1) * x[nn]
                ionize = abs(term.aj2) * x[mm]
                recombination_totals[ion_mm] += recomb
                ionization_totals[ion_mm] += ionize
                component = 0 if term.rate_type == 7 else 1
                recombination_components[component, ion_mm] += recomb
                ionization_components[component, ion_mm] += ionize

    dense_norm = assembly.normalized_matrix.copy()
    try:
        dense_condition = float(np.linalg.cond(dense_norm))
    except np.linalg.LinAlgError:
        dense_condition = float("inf")

    notes: List[str] = list(runtime_notes)
    nnegative = int(np.count_nonzero(x < 0.0))
    if nnegative:
        notes.append("source-faithful Lucy iteration returned negative populations; values were not clipped")
    if any(method == "numpy_lstsq" for method in solver_methods):
        notes.append("one or more condensed solves used least-squares fallback")

    return LucySolveResult(
        populations=x,
        converged=outer_diff <= context.lucy_tolerance and fixed_diff < context.fixed_point_tolerance,
        outer_iterations=outer,
        fixed_point_iterations=total_fixed,
        final_outer_difference=outer_diff,
        final_fixed_point_difference=fixed_diff,
        n_negative_populations=nnegative,
        normalization=normalization,
        normalization_error=abs(normalization - 1.0),
        max_relative_row_residual=float(np.max(relative_residual)),
        max_active_relative_row_residual=max_active_relative_residual,
        l1_row_residual=l1_residual,
        l1_relative_row_residual=l1_relative_residual,
        n_zero_scale_rows=n_zero_scale_rows,
        row_residual=residual.copy(),
        row_scale=raw_row_scale.copy(),
        relative_row_residual=relative_residual.copy(),
        solver_method="+".join(sorted(set(solver_methods))) or "none",
        condensed_rank=condensed_rank,
        condensed_dimension=nspmx,
        dense_rank=int(np.linalg.matrix_rank(dense_norm)),
        dense_condition_number=dense_condition,
        heating=heating,
        cooling=cooling,
        heating2=heating2,
        cooling2=cooling2,
        gamma=gamma,
        alpha=alpha,
        fgamma=fgamma,
        falpha=falpha,
        igammamax_record=igammamax,
        ialphamax_record=ialphamax,
        ion_population_totals=ion_population_totals,
        ionization_totals=ionization_totals,
        recombination_totals=recombination_totals,
        ionization_components=ionization_components,
        recombination_components=recombination_components,
        notes=notes,
        trace=trace,
    )


def solve_element_statistical_equilibrium(
    master: XSTARMasterData,
    derived: XSTARDerivedPointers,
    *,
    element_z: int,
    context: ElementEquilibriumContext,
    dispatcher: Optional[SourceFaithfulUCalc] = None,
) -> ElementEquilibriumResult:
    """Run the complete translated element source sequence."""
    assembly = assemble_element_matrix(
        master,
        derived,
        element_z=element_z,
        context=context,
        dispatcher=dispatcher,
    )
    solve: Optional[LucySolveResult] = None
    if assembly.strict_assembly_ready or not context.strict_context:
        if assembly.terms:
            solve = msolvelucy(assembly, context)
    ready = bool(
        assembly.strict_assembly_ready
        and solve is not None
        and solve.converged
        and solve.n_negative_populations == 0
        and solve.normalization_error <= 1.0e-10
        and assembly.basis.n_rows > 0
    )
    return ElementEquilibriumResult(
        assembly=assembly,
        solve=solve,
        full_element_direct_solve_ready=ready,
    )


def register_element_equilibrium_stage(
    driver: Any,
    *,
    element_z: int,
    context: ElementEquilibriumContext,
    dispatcher: Optional[SourceFaithfulUCalc] = None,
) -> None:
    """Register the translated ELEMENT_POPULATIONS stage on the source driver."""
    from .driver import XSTARStage

    def _handler(state: Any) -> None:
        if state.atomic.master is None or state.atomic.derived is None:
            raise ElementEquilibriumError("atomic database state must be initialized first")
        result = solve_element_statistical_equilibrium(
            state.atomic.master,
            state.atomic.derived,
            element_z=element_z,
            context=context,
            dispatcher=dispatcher,
        )
        state.matrix.compact_matrix = result.assembly.dense_matrix
        state.matrix.rhs = result.assembly.rhs.copy()
        state.matrix.basis_metadata = {
            row.compact_index: {
                "superlevel": row.superlevel,
                "ion_counter": row.ion_counter,
                "roles": row.roles,
            }
            for row in result.assembly.basis.rows
        }
        if result.solve is not None:
            state.plasma.populations = result.solve.populations.copy()
        state.outputs["element_equilibrium"] = result
        state.provenance["element_equilibrium_ready"] = result.full_element_direct_solve_ready

    driver.register(
        XSTARStage.ELEMENT_POPULATIONS,
        _handler,
        source_routines=(
            "levwkelement",
            "levwk",
            "calc_hmc_ion",
            "calc_hmc_element",
            "msolvelucy",
            "leqt2f",
            "ludcmp",
            "lubksb",
            "mprove",
        ),
    )


# ---------------------------------------------------------------------------
# Products


def _write_csv(path: Path, rows: Sequence[Mapping[str, Any]], fieldnames: Sequence[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def write_element_equilibrium_products(
    result: ElementEquilibriumResult,
    out_dir: str | Path,
    *,
    port_version: str = "v0.4.16",
) -> Dict[str, Path]:
    """Write basis, matrix, population, blocker, and summary products."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    assembly = result.assembly
    basis = assembly.basis
    solve = result.solve

    basis_rows: List[Dict[str, Any]] = []
    for row in basis.rows:
        basis_rows.append(
            {
                "compact_index": row.compact_index,
                "superlevel": row.superlevel,
                "ion_counter": row.ion_counter,
                "n_roles": len(row.roles),
                "is_shared_alias": row.is_shared_alias,
                "roles_json": json.dumps(row.roles, sort_keys=True),
            }
        )
    basis_csv = out / "xstar_element_compact_basis.csv"
    _write_csv(basis_csv, basis_rows, list(basis_rows[0]) if basis_rows else [])

    terms_rows = [term.__dict__ for term in assembly.terms]
    terms_csv = out / "xstar_element_matrix_terms.csv"
    _write_csv(terms_csv, terms_rows, list(terms_rows[0]) if terms_rows else ["term_index"])

    ion_rows = []
    for summary in assembly.ion_summaries:
        row = dict(summary.__dict__)
        row["blocked_reasons"] = json.dumps(summary.blocked_reasons, sort_keys=True)
        ion_rows.append(row)
    ions_csv = out / "xstar_element_ion_assembly.csv"
    _write_csv(ions_csv, ion_rows, list(ion_rows[0]) if ion_rows else ["ion_index"])

    blocked_csv = out / "xstar_element_blocked_records.csv"
    blocked_fields = sorted({key for row in assembly.blocked_records for key in row}) or ["record", "reason"]
    _write_csv(blocked_csv, assembly.blocked_records, blocked_fields)

    populations_rows: List[Dict[str, Any]] = []
    for i, row in enumerate(basis.rows, start=1):
        populations_rows.append(
            {
                "compact_index": i,
                "initial_population": float(assembly.initial_populations[i]),
                "solved_population": "" if solve is None else float(solve.populations[i - 1]),
                "superlevel": row.superlevel,
                "ion_counter": row.ion_counter,
                "roles_json": json.dumps(row.roles, sort_keys=True),
            }
        )
    populations_csv = out / "xstar_element_populations.csv"
    _write_csv(populations_csv, populations_rows, list(populations_rows[0]) if populations_rows else [])

    residual_rows: List[Dict[str, Any]] = []
    if solve is not None:
        for i, row in enumerate(basis.rows):
            residual_rows.append(
                {
                    "compact_index": i + 1,
                    "superlevel": row.superlevel,
                    "ion_counter": row.ion_counter,
                    "population": float(solve.populations[i]),
                    "absolute_row_residual": float(abs(solve.row_residual[i])),
                    "signed_row_residual": float(solve.row_residual[i]),
                    "row_equation_scale": float(solve.row_scale[i]),
                    "relative_row_residual": float(solve.relative_row_residual[i]),
                    "active_scale_gt_1e_12": bool(solve.row_scale[i] > 1.0e-12),
                    "zero_scale_row": bool(solve.row_scale[i] <= 1.0e-300),
                }
            )
    residuals_csv = out / "xstar_element_row_residuals.csv"
    _write_csv(
        residuals_csv,
        residual_rows,
        list(residual_rows[0]) if residual_rows else ["compact_index"],
    )

    trace_outputs: Dict[str, Path] = {}
    if solve is not None and solve.trace is not None:
        trace_specs = [
            ("lucy_outer_trace_csv", "xstar_msolvelucy_outer_level_trace.csv", solve.trace.outer_level_rows),
            ("lucy_superlevel_trace_csv", "xstar_msolvelucy_superlevel_trace.csv", solve.trace.superlevel_rows),
            ("lucy_condensed_matrix_trace_csv", "xstar_msolvelucy_condensed_matrix_trace.csv", solve.trace.condensed_matrix_rows),
            ("lucy_fixed_point_trace_csv", "xstar_msolvelucy_fixed_point_trace.csv", solve.trace.fixed_point_rows),
        ]
        for key, filename, rows in trace_specs:
            path = out / filename
            _write_csv(path, rows, list(rows[0]) if rows else ["status"])
            trace_outputs[key] = path

    matrix_npz = out / "xstar_element_matrix.npz"
    np.savez_compressed(
        matrix_npz,
        matrix=assembly.dense_matrix,
        normalized_matrix=assembly.normalized_matrix,
        rhs=assembly.rhs,
        heating_matrix=assembly.heating_matrix,
        heating_matrix2=assembly.heating_matrix2,
        initial_populations=assembly.initial_populations[1:],
        solved_populations=np.asarray([] if solve is None else solve.populations),
        gamma=np.asarray([] if solve is None else solve.gamma),
        alpha=np.asarray([] if solve is None else solve.alpha),
        fgamma=np.asarray([] if solve is None else solve.fgamma),
        falpha=np.asarray([] if solve is None else solve.falpha),
        ion_population_totals=np.asarray([] if solve is None else solve.ion_population_totals),
        ionization_totals=np.asarray([] if solve is None else solve.ionization_totals),
        recombination_totals=np.asarray([] if solve is None else solve.recombination_totals),
        ionization_components=np.asarray([] if solve is None else solve.ionization_components),
        recombination_components=np.asarray([] if solve is None else solve.recombination_components),
        row_residual=np.asarray([] if solve is None else solve.row_residual),
        row_scale=np.asarray([] if solve is None else solve.row_scale),
        relative_row_residual=np.asarray([] if solve is None else solve.relative_row_residual),
        nsup=basis.nsup[1:],
        nion=basis.nion[1:],
    )

    summary: Dict[str, Any] = {
        "port_version": port_version,
        "status": "element_statistical_equilibrium_subsystem_completed",
        "element_z": basis.element_z,
        "min_ion_stage": basis.min_ion_stage,
        "max_ion_stage": basis.max_ion_stage,
        "n_compact_rows": basis.n_rows,
        "n_ion_blocks": len(basis.blocks),
        "n_superlevels": basis.n_superlevels,
        "normalization_row": basis.normalization_row,
        "n_shared_alias_rows": sum(row.is_shared_alias for row in basis.rows),
        "n_records_seen": assembly.n_records_seen,
        "n_records_evaluated": assembly.n_records_evaluated,
        "n_records_source_noop": assembly.n_records_source_noop,
        "n_records_skipped": assembly.n_records_skipped,
        "n_records_blocked": assembly.n_records_blocked,
        "n_unmapped_matrix_endpoints": assembly.n_unmapped_endpoints,
        "n_source_ipmat_endpoint_clamps": assembly.n_source_ipmat_endpoint_clamps,
        "n_matrix_terms": len(assembly.terms),
        "strict_matrix_assembly_ready": assembly.strict_assembly_ready,
        "source_sequence_complete": result.source_sequence_complete,
        "full_element_direct_solve_ready": result.full_element_direct_solve_ready,
        "six_row_and_119_row_products_role": "regression_subsets_only",
        "production_acceptance_target": f"full_{basis.n_rows}_row_element_matrix_and_population_vector",
    }
    parity = result.population_parity
    matrix_parity = result.full_element_matrix_parity
    if not assembly.strict_assembly_ready:
        dominant_next_target = "resolve_remaining_element_matrix_assembly_blockers"
    elif solve is None:
        dominant_next_target = "execute_full_element_population_solve"
    elif not solve.converged or solve.n_negative_populations > 0:
        dominant_next_target = "resolve_msolvelucy_convergence"
    elif not result.full_element_direct_solve_ready:
        dominant_next_target = "resolve_full_element_execution_acceptance"
    elif matrix_parity is not None and not matrix_parity.full_element_matrix_parity_ready:
        dominant_next_target = matrix_parity.diagnosis
    elif parity is None:
        dominant_next_target = "run_xstar_population_parity_gate_before_generalization"
    elif not parity.xstar_population_parity_ready:
        dominant_next_target = parity.diagnosis
    elif result.msolvelucy_state_parity is None:
        dominant_next_target = "run_msolvelucy_iteration_state_parity_before_generalization"
    elif not result.msolvelucy_state_parity.msolvelucy_state_parity_ready:
        dominant_next_target = result.msolvelucy_state_parity.diagnosis
    else:
        dominant_next_target = "generalize_population_validated_element_solve_then_local_ionization_thermal_closure"
    summary["dominant_next_target"] = dominant_next_target
    summary["full_element_matrix_parity_supplied"] = matrix_parity is not None
    summary["full_element_matrix_parity_ready"] = bool(
        matrix_parity and matrix_parity.full_element_matrix_parity_ready
    )
    if matrix_parity is not None:
        summary["full_element_matrix_parity_diagnosis"] = matrix_parity.diagnosis
        summary["full_element_matrix_first_failing_data_type"] = matrix_parity.first_failing_data_type
        summary["full_element_matrix_first_failing_rate_type"] = matrix_parity.first_failing_rate_type
    summary["xstar_population_parity_supplied"] = parity is not None
    summary["xstar_population_parity_ready"] = bool(parity and parity.xstar_population_parity_ready)
    summary["milestone3_population_parity_ready"] = bool(parity and parity.xstar_population_parity_ready)
    if parity is not None:
        summary["population_parity_diagnosis"] = parity.diagnosis
        summary["selected_xstar_solve_call_id"] = parity.reference.solve_call_id
        summary["python_initial_vs_xstar_before_l1"] = parity.initial_metrics.l1_difference
        summary["python_native_final_vs_xstar_after_l1"] = parity.native_final_metrics.l1_difference
        summary["python_xstar_before_seeded_final_vs_xstar_after_l1"] = (
            None if parity.seeded_final_metrics is None else parity.seeded_final_metrics.l1_difference
        )
    state_parity = result.msolvelucy_state_parity
    summary["msolvelucy_state_parity_supplied"] = state_parity is not None
    summary["msolvelucy_state_parity_ready"] = bool(state_parity and state_parity.msolvelucy_state_parity_ready)
    if state_parity is not None:
        summary["msolvelucy_state_parity_diagnosis"] = state_parity.diagnosis
        summary["msolvelucy_first_failing_component"] = state_parity.first_failing_component
        summary["msolvelucy_first_failing_comparison_key"] = state_parity.first_failing_comparison_key
        summary["msolvelucy_first_failing_outer_iteration"] = state_parity.first_failing_outer_iteration
        summary["msolvelucy_first_failing_fixed_iteration"] = state_parity.first_failing_fixed_iteration

    if solve is not None:
        summary.update(
            {
                "solver_converged": solve.converged,
                "solver_method": solve.solver_method,
                "outer_iterations": solve.outer_iterations,
                "fixed_point_iterations": solve.fixed_point_iterations,
                "final_outer_difference": solve.final_outer_difference,
                "final_fixed_point_difference": solve.final_fixed_point_difference,
                "n_negative_populations": solve.n_negative_populations,
                "population_normalization": solve.normalization,
                "population_normalization_error": solve.normalization_error,
                "max_relative_row_residual": solve.max_relative_row_residual,
                "max_active_relative_row_residual": solve.max_active_relative_row_residual,
                "l1_row_residual": solve.l1_row_residual,
                "l1_relative_row_residual": solve.l1_relative_row_residual,
                "n_zero_scale_rows": solve.n_zero_scale_rows,
                "lucy_trace_captured": solve.trace is not None,
                "condensed_matrix_rank": solve.condensed_rank,
                "condensed_matrix_dimension": solve.condensed_dimension,
                "dense_normalized_matrix_rank": solve.dense_rank,
                "dense_normalized_matrix_condition_number": solve.dense_condition_number,
                "heating": solve.heating,
                "cooling": solve.cooling,
                "heating2": solve.heating2,
                "cooling2": solve.cooling2,
                "solver_notes": solve.notes,
            }
        )
    else:
        summary.update({"solver_converged": False, "solver_status": "not_run_due_to_incomplete_strict_assembly"})

    json_path = out / "xstar_element_equilibrium_summary.json"
    json_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    markdown_path = out / "xstar_element_equilibrium_summary.md"
    lines = [
        "# XSTAR source-faithful element statistical-equilibrium subsystem",
        "",
        f"- Port version: `{port_version}`",
        f"- Element Z: `{basis.element_z}`",
        f"- Ion stages: `{basis.min_ion_stage}`–`{basis.max_ion_stage}`",
        f"- Compact rows: `{basis.n_rows}`",
        f"- Shared alias rows: `{summary['n_shared_alias_rows']}`",
        f"- Matrix terms: `{len(assembly.terms)}`",
        f"- Blocked records: `{assembly.n_records_blocked}`",
        f"- Unmapped endpoints: `{assembly.n_unmapped_endpoints}`",
        f"- Source ipmat endpoint clamps: `{assembly.n_source_ipmat_endpoint_clamps}`",
        f"- Strict matrix assembly ready: `{assembly.strict_assembly_ready}`",
        f"- Solver converged: `{summary.get('solver_converged')}`",
        f"- Full direct solve ready: `{result.full_element_direct_solve_ready}`",
        f"- Full record-matrix parity ready: `{bool(matrix_parity and matrix_parity.full_element_matrix_parity_ready)}`",
        f"- XSTAR population parity supplied: `{parity is not None}`",
        f"- XSTAR population parity ready: `{bool(parity and parity.xstar_population_parity_ready)}`",
        f"- `msolvelucy` state parity ready: `{bool(result.msolvelucy_state_parity and result.msolvelucy_state_parity.msolvelucy_state_parity_ready)}`",
        f"- Dominant next target: `{dominant_next_target}`",
        "",
        "The six-row and 119-row products are retained only as regression subsets; "
        "the acceptance target is the complete compact element matrix and population vector.",
    ]
    markdown_path.write_text("\n".join(lines) + "\n")

    return {
        "basis_csv": basis_csv,
        "terms_csv": terms_csv,
        "ions_csv": ions_csv,
        "blocked_csv": blocked_csv,
        "populations_csv": populations_csv,
        "residuals_csv": residuals_csv,
        "matrix_npz": matrix_npz,
        "json": json_path,
        "markdown": markdown_path,
        **trace_outputs,
    }
