"""Python tools for reading and evaluating XSTAR's packed ``atdb.fits`` atomic database."""

__version__ = "0.5.23"

# Pure-Python public API infrastructure.  These remain importable even on
# systems where astropy is not available yet.
from .context import LocalPlasmaState, RadiationField, EscapeContext, XSTARContext, context_from_values, context_from_xstar_run
from .rates_type50 import RateEvaluation, evaluate_type50_bound_bound, evaluate_type50_ucalc_record
from .rates_type51 import evaluate_type51_ucalc_record
from .rates_type71 import evaluate_calt71_record, evaluate_type71_ucalc_record
from .rates_type53 import Type53LiveRadiationState, Type53PhintResult, evaluate_phint53_exact, evaluate_type53_ucalc_record
from .xstar_type53_live_native_parity import build_type53_live_native_parity_audit, write_type53_live_native_parity_audit
from .xstar_priority_native_type53_integration import build_priority_native_type53_integration_audit, write_priority_native_type53_integration_audit
from .xstar_type50_type71_native_parity import (
    build_type50_type71_native_parity_audit,
    write_type50_type71_native_parity_audit,
)
from .xstar_priority_native_type50_type71_integration import (
    build_priority_native_type50_type71_integration_audit,
    write_priority_native_type50_type71_integration_audit,
)
from .audit import type50_line_pumping
from .benchmark import (
    XSTARLocalTarget,
    XSTARBenchmarkComparison,
    default_helike_benchmark_cases,
    write_default_helike_cases_csv,
    build_xstar_local_target,
    compare_solver_to_xstar_target,
    reproduce_xstar_run,
    run_xstar_benchmark_suite,
    write_xstar_benchmark_outputs,
    write_xstar_benchmark_suite,
    solver_kwargs_from_preset,
    xstar_local_state_solver_kwargs,
)

from .xstar_run import (
    XSTARInputParameters,
    XSTAROutputProductSpec,
    parse_xstar_command,
    parse_xstar_command_file,
    standard_xstar_output_products,
    xstar_recreation_plan,
    write_xstar_recreation_plan,
)
from .xstar_state import (
    XSTARContinuumState,
    XSTARLineTransferState,
    XSTARZoneState,
    XSTARRunState,
    required_live_state_fields,
    create_initial_xstar_run_state,
    create_initial_xstar_run_state_from_input,
    write_xstar_state_skeleton,
)

from .xstar_detail import (
    read_xstar_parameters_from_run_dir,
    reconstruct_bremsa_from_detal4_rows,
    reconstruct_bremsint,
    read_xstar_detail_run_state,
    summarize_xstar_detail_state,
    write_xstar_detail_state,
    pescl_xstar,
    ptmp_from_tau_xstar,
    xstar_nbinc_index,
    type50_vtherm_xstar,
    audit_xstar_detail_type50_rates,
    write_xstar_detail_type50_rate_audit,
)

from .xstar_source_provenance import (
    audit_xstar_live_bremsa_source_path,
    write_xstar_live_bremsa_source_path_audit,
    summarize_bremsa_variant_gap,
)


from .xstar_live_rate_grid_probe import (
    LiveRateGridState,
    live_rate_grid_probe_schema_rows,
    read_live_rate_grid_probe_csv,
    summarize_live_rate_grid_probe_csv,
    prepare_live_rate_grid_probe_products,
)


from .xstar_matrix_parity import (
    audit_type53_live_bremsam_phint53,
    write_type53_live_bremsam_phint53_audit,
    audit_type53_live_bremsam_matrix_replacement,
    write_type53_live_bremsam_matrix_replacement_audit,
)

from .xstar_full_parity_closure import (
    audit_source_code_equivalent_local_closure,
    write_source_code_equivalent_local_closure_audit,
    matrix_family_closure_summary,
)

from .xstar_full_parity_probes import (
    prepare_full_parity_probe_products,
    summarize_full_parity_probe_csvs,
    read_ucalc_record_probe_csv,
    read_calc_hmc_ion_matrix_probe_csv,
)

from .xstar_record_level_replay import (
    apply_record_level_ucalc_replay,
    audit_record_level_ucalc_matrix_replay,
    write_record_level_ucalc_matrix_replay_audit,
)

from .xstar_population_closure_diagnosis import (
    diagnose_population_closure_from_family_scan,
    write_population_closure_diagnosis,
)

from .xstar_population_closure_probe import (
    population_closure_probe_schema_rows,
    summarize_population_closure_probe_csv,
    write_population_closure_probe_products,
)

from .xstar_calc_hmc_all_probe import (
    calc_hmc_all_probe_helper,
    calc_hmc_all_insertion_snippets,
    write_calc_hmc_all_probe_products,
)


from .xstar_dsec_probe import (
    dsec_probe_helper,
    dsec_insertion_snippets,
    write_dsec_probe_products,
)

from .xstar_msolvelucy_state_probe import (
    msolvelucy_state_probe_helper,
    msolvelucy_insertion_snippets,
    write_msolvelucy_state_probe_products,
)

from .xstar_full_element_basis import (
    build_full_element_basis_scaffold,
    write_full_element_basis_scaffold,
)

from .source_port import (
    ElementEquilibriumError, ElementIonBlock, ElementBasisRow, ElementCompactBasis,
    EscapeProbabilityContext, ElementEquilibriumContext, MatrixTerm, IonAssemblySummary,
    ElementMatrixAssembly, LucyIterationTrace, LucySolveResult, ElementEquilibriumResult,
    build_level_table, build_element_compact_basis, map_global_populations_to_compact_basis, levwk, levwkelement,
    assemble_element_matrix, msolvelucy, solve_element_statistical_equilibrium,
    register_element_equilibrium_stage, write_element_equilibrium_products,
    IonBalanceError, CalcIonRatesContext, CalcIonRateContribution,
    CalcIonRatesResult, IoneqmResult, IstrucResult, IonStageLimitResult,
    calc_ion_rates, ioneqm, istruc, select_ion_stage_limits,
    calc_element_pre_matrix_balance,
    CalcHMCAllError, FixedStateElementRequest, FixedStateContinuumResult,
    FixedStateElementResult, FixedStateCalcHMCAllResult,
    resolve_calc_hmc_all_density, calc_hmc_all, register_fixed_state_calc_hmc_all,
    write_fixed_state_calc_hmc_all_products,
    AllElementFixedStateError, OxygenCall73RegressionGate,
    OXYGEN_CALL73_REQUIRED_TRUE_FIELDS, validate_oxygen_call73_regression,
    AllElementProbeElement, AllElementFixedStatePlan, AllElementFixedStateRun,
    load_all_element_fixed_state_plan, build_all_element_fixed_state_requests,
    run_all_element_fixed_state, write_all_element_fixed_state_products,
    CalcHMCAllParityError, CalcHMCAllProbeCritfReference,
    CalcHMCAllProbeElementReference, CalcHMCAllParityRow,
    CalcHMCAllPreContinuumParityResult, SameCallMatrixParityResult,
    ThermalFamilyParityResult, Rate7CJ2DiagnosisResult,
    MSolveLucyFinalSnapshotParityResult, MSolveLucyInitialStateError,
    MSolveLucyInitialPopulationReference, MSolveLucyInitialPopulationParityResult,
    load_msolvelucy_initial_population_reference, compare_msolvelucy_initial_population,
    load_calc_hmc_all_probe_critf,
    load_calc_hmc_all_probe_element_reference, compare_same_call_matrix_terms,
    compare_thermal_families, diagnose_rate7_cj2_records,
    compare_msolvelucy_final_snapshot, compare_calc_hmc_all_pre_continuum_probe,
    write_calc_hmc_all_pre_continuum_parity_products,
    PopulationParityError, XSTARPopulationReference, XSTARRuntimeContextReference, PopulationMetrics,
    ElementPopulationParityResult, load_xstar_population_reference, load_xstar_runtime_context_reference,
    compare_element_population_parity, write_element_population_parity_products,
    MSolveStateParityError, StateComponentMetrics, MSolveStateParityResult,
    compare_msolvelucy_state_probe, write_msolvelucy_state_parity_products,
    FullElementMatrixParityError, MatrixFamilyParityMetrics,
    FullElementMatrixParityResult, compare_full_element_matrix_probe,
    write_full_element_matrix_parity_products,
    EscapeStateError, EscapeStateBuildResult, load_escape_state_from_xstar_run,
    write_escape_state_npz, write_escape_state_summary,
    DsecPortError, DSEC_CHARGE_TOLERANCE, DSEC_THERMAL_TOLERANCE,
    DSEC_TEMPERATURE_STAGNATION_TOLERANCE, DSEC_TEMPERATURE_FACTOR,
    DSEC_ELECTRON_FACTOR, DsecMutableRuntimeState, DsecEvaluation,
    DsecEvaluator, CalcHMCAllDsecEvaluator, DsecTrajectoryEvent,
    DsecResult, dsec, write_dsec_trajectory_products, load_python_dsec_trajectory, DsecProbeTrajectory,
    load_xstar_dsec_trajectory, DsecTrajectoryParityRow,
    DsecTrajectoryParityResult, compare_dsec_trajectory,
    write_dsec_trajectory_parity_products, V0444CompleteFixedStateRegressionGate,
    validate_v0444_complete_fixed_state_regression, DsecAcceptanceResult,
    build_dsec_acceptance, write_dsec_acceptance_products,
    PhysicalDsecInitialState, PhysicalDsecContinuumTemplate,
    PhysicalDsecCalcKwargsFactory, initial_state_from_xstar_trajectory,
    build_physical_dsec_runtime_state,
    apply_dsec_matching_input_state,
    clone_physical_dsec_runtime_state,
)


from .source_port import (
    XSTAR_HEATF_KT_EV_PER_T4, XSTAR_HEATF_ERG_PER_EV,
    XSTAR_HEATF_RESIDUAL_FLOOR, XSTAR_HEATF_RESIDUAL_FACTOR,
    HeatFPortError, HeatFContext, HeatFResult, HeatFProbeReference,
    HeatFParityResult, heatf, heatf_continuum_result,
    load_heatf_probe_reference, compare_heatf_probe,
    write_heatf_parity_products, V0441_BREMEM_REQUIRED_TRUE_FIELDS,
    V0441BremsstrahlungRegressionGate, validate_v0441_bremem_regression,
)

from .workflow import (
    TripletResult,
    open_database,
    get_levels,
    get_lines,
    get_wavelengths,
    get_energies,
    match_line,
    match_lines,
    get_collisions,
    get_photoionization,
    get_recombination,
    calc_emissivity,
    calc_rate,
    calc_triplet,
    solve_populations,
    build_matrix,
)

try:
    from .hierarchy import ATDB
    from .api import XSTARAtomic, parse_ion
    from .data import download_data, find_atdb_file, get_data_path, get_data_paths, resolve_atdb_path, set_data_path
    from .xstar_element_solver import solve_element_reference
except ModuleNotFoundError as exc:  # pragma: no cover - optional dependency guard
    if exc.name != "astropy":
        raise

    def _missing_astropy(*args, **kwargs):
        raise ImportError("This xstar_atomic feature requires astropy. Install package dependencies or `pip install astropy`.")

    ATDB = _missing_astropy  # type: ignore
    XSTARAtomic = _missing_astropy  # type: ignore
    parse_ion = _missing_astropy  # type: ignore
    download_data = _missing_astropy  # type: ignore
    find_atdb_file = _missing_astropy  # type: ignore
    get_data_path = _missing_astropy  # type: ignore
    get_data_paths = _missing_astropy  # type: ignore
    resolve_atdb_path = _missing_astropy  # type: ignore
    set_data_path = _missing_astropy  # type: ignore
    solve_element_reference = _missing_astropy  # type: ignore

__all__ = [
    "ATDB",
    "XSTARAtomic",
    "parse_ion",
    "download_data",
    "find_atdb_file",
    "get_data_path",
    "get_data_paths",
    "resolve_atdb_path",
    "set_data_path",
    "solve_element_reference",
    "LocalPlasmaState",
    "RadiationField",
    "EscapeContext",
    "XSTARContext",
    "context_from_values",
    "context_from_xstar_run",
    "RateEvaluation",
    "evaluate_type50_bound_bound",
    "evaluate_type50_ucalc_record",
    "evaluate_type51_ucalc_record",
    "evaluate_calt71_record",
    "evaluate_type71_ucalc_record",
    "Type53LiveRadiationState",
    "Type53PhintResult",
    "evaluate_phint53_exact",
    "evaluate_type53_ucalc_record",
    "build_type53_live_native_parity_audit",
    "write_type53_live_native_parity_audit",
    "build_priority_native_type53_integration_audit",
    "write_priority_native_type53_integration_audit",
    "build_type50_type71_native_parity_audit",
    "write_type50_type71_native_parity_audit",
    "build_priority_native_type50_type71_integration_audit",
    "write_priority_native_type50_type71_integration_audit",
    "type50_line_pumping",
    "XSTARLocalTarget",
    "XSTARBenchmarkComparison",
    "default_helike_benchmark_cases",
    "write_default_helike_cases_csv",
    "build_xstar_local_target",
    "compare_solver_to_xstar_target",
    "reproduce_xstar_run",
    "run_xstar_benchmark_suite",
    "write_xstar_benchmark_outputs",
    "write_xstar_benchmark_suite",
    "solver_kwargs_from_preset",
    "xstar_local_state_solver_kwargs",
    "TripletResult",
    "open_database",
    "get_levels",
    "get_lines",
    "get_wavelengths",
    "get_energies",
    "match_line",
    "match_lines",
    "get_collisions",
    "get_photoionization",
    "get_recombination",
    "calc_emissivity",
    "calc_rate",
    "calc_triplet",
    "solve_populations",
    "build_matrix",
    "XSTARInputParameters",
    "XSTAROutputProductSpec",
    "parse_xstar_command",
    "parse_xstar_command_file",
    "standard_xstar_output_products",
    "xstar_recreation_plan",
    "write_xstar_recreation_plan",
    "XSTARContinuumState",
    "XSTARLineTransferState",
    "XSTARZoneState",
    "XSTARRunState",
    "required_live_state_fields",
    "create_initial_xstar_run_state",
    "create_initial_xstar_run_state_from_input",
    "write_xstar_state_skeleton",
    "read_xstar_parameters_from_run_dir",
    "reconstruct_bremsa_from_detal4_rows",
    "reconstruct_bremsint",
    "read_xstar_detail_run_state",
    "summarize_xstar_detail_state",
    "write_xstar_detail_state",
    "LiveRateGridState",
    "live_rate_grid_probe_schema_rows",
    "read_live_rate_grid_probe_csv",
    "summarize_live_rate_grid_probe_csv",
    "prepare_live_rate_grid_probe_products",
    "audit_type53_live_bremsam_phint53",
    "write_type53_live_bremsam_phint53_audit",
    "audit_type53_live_bremsam_matrix_replacement",
    "write_type53_live_bremsam_matrix_replacement_audit",
    "audit_source_code_equivalent_local_closure",
    "write_source_code_equivalent_local_closure_audit",
    "matrix_family_closure_summary",
    "apply_record_level_ucalc_replay",
    "audit_record_level_ucalc_matrix_replay",
    "write_record_level_ucalc_matrix_replay_audit",
    "population_closure_probe_schema_rows",
    "summarize_population_closure_probe_csv",
    "write_population_closure_probe_products",
    "msolvelucy_state_probe_helper",
    "msolvelucy_insertion_snippets",
    "write_msolvelucy_state_probe_products",
]

from .xstar_priority_matrix_closure import (
    build_priority_matrix_closure_audit,
    write_priority_matrix_closure_audit,
)

from .xstar_priority_conditional_solve import (
    build_priority_conditional_solve_audit,
    write_priority_conditional_solve_audit,
)


# Source-faithful full-XSTAR Python port infrastructure (v0.4 series).
from .source_port import (
    FortranArray,
    FortranRuntimeError,
    XSTARPythonState,
    XSTARSourceRoutine,
    XSTARCALC_SOURCE_ORDER,
    XSTARCALC_FIXED_STATE_ORDER,
    ZONE_SOURCE_ORDER,
    XSTARStage,
    XSTARPythonDriver,
    UnportedXSTARSourceRoutine,
    UnportedXSTARRoutine,
    UCalcDispatcher,
    default_ucalc_dispatcher,
    UCalcLevel,
    UCalcLevelTable,
    UCalcRecord,
    UCalcContext,
    UCalcStatus,
    UCalcProvenance,
    UCalcResult,
    UCalcExecutionError,
    UCalcUntranslatedBranch,
    UCalcBranchSpec,
    SourceFaithfulUCalc,
    complete_ucalc_branch_catalog,
    default_source_faithful_ucalc,
    build_ucalc_data_type_inventory,
    build_ucalc_branch_catalog_rows,
    build_ucalc_index_only_samples,
    write_ucalc_subsystem_products,
    build_source_inventory,
    write_source_inventory,
    default_port_ledger,
    AtomicDatabaseError,
    PackedRecordHeader,
    XSTARMasterData,
    XSTARDerivedPointers,
    DBWK2Instruction,
    readtbl,
    setptrs,
    dbwk2,
    load_atomic_database_state,
    register_atomic_database_stages,
    default_derived_pointer_cache_path,
    save_derived_pointer_cache,
    load_derived_pointer_cache,
    write_atomic_database_products,
    XSTARLinearAlgebraError, LUDecomposition, LinearSolveResult,
    ludcmp, lubksb, mprove, leqt2f,
    ElementEquilibriumError,
    ElementIonBlock,
    ElementBasisRow,
    ElementCompactBasis,
    EscapeProbabilityContext,
    ElementEquilibriumContext,
    MatrixTerm,
    IonAssemblySummary,
    ElementMatrixAssembly,
    LucyIterationTrace,
    LucySolveResult,
    ElementEquilibriumResult,
    build_level_table,
    build_element_compact_basis,
    map_global_populations_to_compact_basis,
    levwk,
    levwkelement,
    assemble_element_matrix,
    msolvelucy,
    solve_element_statistical_equilibrium,
    register_element_equilibrium_stage,
    write_element_equilibrium_products,
    IonBalanceError,
    CalcIonRatesContext,
    CalcIonRateContribution,
    CalcIonRatesResult,
    IoneqmResult,
    IstrucResult,
    IonStageLimitResult,
    calc_ion_rates,
    ioneqm,
    istruc,
    select_ion_stage_limits,
    calc_element_pre_matrix_balance,
    CalcHMCAllError,
    FixedStateElementRequest,
    FixedStateContinuumResult,
    FixedStateElementResult,
    FixedStateCalcHMCAllResult,
    resolve_calc_hmc_all_density,
    calc_hmc_all,
    register_fixed_state_calc_hmc_all,
    write_fixed_state_calc_hmc_all_products,
    CalcHMCAllParityError,
    CalcHMCAllProbeCritfReference,
    CalcHMCAllProbeElementReference,
    CalcHMCAllParityRow,
    CalcHMCAllPreContinuumParityResult,
    SameCallMatrixParityResult,
    ThermalFamilyParityResult,
    Rate7CJ2DiagnosisResult,
    MSolveLucyFinalSnapshotParityResult,
    MSolveLucyInitialStateError,
    MSolveLucyInitialPopulationReference,
    MSolveLucyInitialPopulationParityResult,
    load_msolvelucy_initial_population_reference,
    compare_msolvelucy_initial_population,
    load_calc_hmc_all_probe_critf,
    load_calc_hmc_all_probe_element_reference,
    compare_same_call_matrix_terms,
    compare_thermal_families,
    diagnose_rate7_cj2_records,
    compare_msolvelucy_final_snapshot,
    compare_calc_hmc_all_pre_continuum_probe,
    write_calc_hmc_all_pre_continuum_parity_products,
    PopulationParityError,
    XSTARPopulationReference,
    XSTARRuntimeContextReference,
    PopulationMetrics,
    ElementPopulationParityResult,
    load_xstar_population_reference,
    load_xstar_runtime_context_reference,
    compare_element_population_parity,
    write_element_population_parity_products,
    MSolveStateParityError,
    StateComponentMetrics,
    MSolveStateParityResult,
    compare_msolvelucy_state_probe,
    write_msolvelucy_state_parity_products,
    XSTAR_BREMEM_CC,
    XSTAR_BREMEM_KT_EV_PER_T4,
    XSTAR_BREMEM_ION_Z2_FACTOR,
    XSTAR_BREMEM_GAMMA_FACTOR,
    XSTAR_BREMEM_ION_CHARGE,
    XSTAR_BREMEM_GAUNT_FACTOR,
    BremsstrahlungPortError,
    BremsstrahlungContext,
    BremsstrahlungResult,
    BremsstrahlungProbeReference,
    BremsstrahlungParityResult,
    bremem,
    bremem_continuum_result,
    load_bremem_probe_reference,
    compare_bremem_probe,
    write_bremem_parity_products,
    V0440_FREEF_REQUIRED_TRUE_FIELDS,
    V0440FreeFreeRegressionGate,
    validate_v0440_freef_regression,
)

__all__.extend([
    "FortranArray",
    "FortranRuntimeError",
    "XSTARPythonState",
    "XSTARSourceRoutine",
    "XSTARCALC_SOURCE_ORDER",
    "XSTARCALC_FIXED_STATE_ORDER",
    "ZONE_SOURCE_ORDER",
    "XSTARStage",
    "XSTARPythonDriver",
    "UnportedXSTARSourceRoutine",
    "UnportedXSTARRoutine",
    "UCalcLevel",
    "UCalcLevelTable",
    "UCalcRecord",
    "UCalcContext",
    "UCalcStatus",
    "UCalcProvenance",
    "UCalcResult",
    "UCalcExecutionError",
    "UCalcUntranslatedBranch",
    "UCalcBranchSpec",
    "SourceFaithfulUCalc",
    "complete_ucalc_branch_catalog",
    "default_source_faithful_ucalc",
    "build_ucalc_data_type_inventory",
    "build_ucalc_branch_catalog_rows",
    "build_ucalc_index_only_samples",
    "write_ucalc_subsystem_products",
    "UCalcDispatcher",
    "default_ucalc_dispatcher",
    "build_source_inventory",
    "write_source_inventory",
    "default_port_ledger",
    "AtomicDatabaseError",
    "PackedRecordHeader",
    "XSTARMasterData",
    "XSTARDerivedPointers",
    "DBWK2Instruction",
    "readtbl",
    "setptrs",
    "dbwk2",
    "load_atomic_database_state",
    "register_atomic_database_stages",
    "save_derived_pointer_cache",
    "load_derived_pointer_cache",
    "write_atomic_database_products",
    "XSTARLinearAlgebraError",
    "LUDecomposition",
    "LinearSolveResult",
    "ludcmp",
    "lubksb",
    "mprove",
    "leqt2f",
    "ElementEquilibriumError",
    "ElementIonBlock",
    "ElementBasisRow",
    "ElementCompactBasis",
    "EscapeProbabilityContext",
    "EscapeStateError",
    "EscapeStateBuildResult",
    "load_escape_state_from_xstar_run",
    "write_escape_state_npz",
    "write_escape_state_summary",
    "ElementEquilibriumContext",
    "MatrixTerm",
    "IonAssemblySummary",
    "ElementMatrixAssembly",
    "LucyIterationTrace",
    "LucySolveResult",
    "ElementEquilibriumResult",
    "build_level_table",
    "build_element_compact_basis",
    "map_global_populations_to_compact_basis",
    "levwk",
    "levwkelement",
    "assemble_element_matrix",
    "msolvelucy",
    "solve_element_statistical_equilibrium",
    "register_element_equilibrium_stage",
    "write_element_equilibrium_products",
    "CalcHMCAllError",
    "FixedStateElementRequest",
    "FixedStateContinuumResult",
    "FixedStateElementResult",
    "FixedStateCalcHMCAllResult",
    "resolve_calc_hmc_all_density",
    "calc_hmc_all",
    "register_fixed_state_calc_hmc_all",
    "write_fixed_state_calc_hmc_all_products",
    "AllElementFixedStateError",
    "OxygenCall73RegressionGate",
    "OXYGEN_CALL73_REQUIRED_TRUE_FIELDS",
    "validate_oxygen_call73_regression",
    "AllElementProbeElement",
    "AllElementFixedStatePlan",
    "AllElementFixedStateRun",
    "load_all_element_fixed_state_plan",
    "build_all_element_fixed_state_requests",
    "run_all_element_fixed_state",
    "write_all_element_fixed_state_products",
    "CalcHMCAllParityError",
    "CalcHMCAllProbeCritfReference",
    "CalcHMCAllProbeElementReference",
    "CalcHMCAllParityRow",
    "CalcHMCAllPreContinuumParityResult",
    "SameCallMatrixParityResult",
    "ThermalFamilyParityResult",
    "Rate7CJ2DiagnosisResult",
    "MSolveLucyFinalSnapshotParityResult",
    "MSolveLucyInitialStateError",
    "MSolveLucyInitialPopulationReference",
    "MSolveLucyInitialPopulationParityResult",
    "load_msolvelucy_initial_population_reference",
    "compare_msolvelucy_initial_population",
    "load_calc_hmc_all_probe_critf",
    "load_calc_hmc_all_probe_element_reference",
    "compare_same_call_matrix_terms",
    "compare_thermal_families",
    "diagnose_rate7_cj2_records",
    "compare_msolvelucy_final_snapshot",
    "compare_calc_hmc_all_pre_continuum_probe",
    "write_calc_hmc_all_pre_continuum_parity_products",
    "PopulationParityError",
    "XSTARPopulationReference",
    "XSTARRuntimeContextReference",
    "PopulationMetrics",
    "ElementPopulationParityResult",
    "load_xstar_population_reference",
    "load_xstar_runtime_context_reference",
    "compare_element_population_parity",
    "write_element_population_parity_products",
    "MSolveStateParityError",
    "StateComponentMetrics",
    "MSolveStateParityResult",
    "compare_msolvelucy_state_probe",
    "write_msolvelucy_state_parity_products",
    "XSTAR_BREMEM_CC",
    "XSTAR_BREMEM_KT_EV_PER_T4",
    "XSTAR_BREMEM_ION_Z2_FACTOR",
    "XSTAR_BREMEM_GAMMA_FACTOR",
    "XSTAR_BREMEM_ION_CHARGE",
    "XSTAR_BREMEM_GAUNT_FACTOR",
    "BremsstrahlungPortError",
    "BremsstrahlungContext",
    "BremsstrahlungResult",
    "BremsstrahlungProbeReference",
    "BremsstrahlungParityResult",
    "bremem",
    "bremem_continuum_result",
    "load_bremem_probe_reference",
    "compare_bremem_probe",
    "write_bremem_parity_products",
    "V0440_FREEF_REQUIRED_TRUE_FIELDS",
    "V0440FreeFreeRegressionGate",
    "validate_v0440_freef_regression",
    "FullElementMatrixParityError",
    "MatrixFamilyParityMetrics",
    "FullElementMatrixParityResult",
    "compare_full_element_matrix_probe",
    "write_full_element_matrix_parity_products",
])

__all__.extend([
    "calc_hmc_all_probe_helper",
    "calc_hmc_all_insertion_snippets",
    "write_calc_hmc_all_probe_products",
])


__all__.extend([
    "dsec_probe_helper",
    "dsec_insertion_snippets",
    "write_dsec_probe_products",
    "DsecPortError",
    "DSEC_CHARGE_TOLERANCE",
    "DSEC_THERMAL_TOLERANCE",
    "DSEC_TEMPERATURE_STAGNATION_TOLERANCE",
    "DSEC_TEMPERATURE_FACTOR",
    "DSEC_ELECTRON_FACTOR",
    "DsecMutableRuntimeState",
    "DsecEvaluation",
    "DsecEvaluator",
    "CalcHMCAllDsecEvaluator",
    "DsecTrajectoryEvent",
    "DsecResult",
    "dsec",
    "write_dsec_trajectory_products",
    "load_python_dsec_trajectory",
    "DsecProbeTrajectory",
    "load_xstar_dsec_trajectory",
    "DsecTrajectoryParityRow",
    "DsecTrajectoryParityResult",
    "compare_dsec_trajectory",
    "write_dsec_trajectory_parity_products",
    "V0444CompleteFixedStateRegressionGate",
    "validate_v0444_complete_fixed_state_regression",
    "DsecAcceptanceResult",
    "build_dsec_acceptance",
    "write_dsec_acceptance_products",
    "PhysicalDsecInitialState",
    "PhysicalDsecContinuumTemplate",
    "PhysicalDsecCalcKwargsFactory",
    "initial_state_from_xstar_trajectory",
    "build_physical_dsec_runtime_state",
    "apply_dsec_matching_input_state",
    "clone_physical_dsec_runtime_state",
])

from .source_port.emissivity import (
    CalcEmisabPortError,
    CalcEmisabWorkspace,
    CalcEmisabContext,
    CalcEmisabRecordTrace,
    CalcEmisabIonTrace,
    CalcEmisabElementTrace,
    CalcEmisabResult,
    resolve_calc_emisab_density,
    calc_emisab_ion,
    calc_emisab_element,
    calc_emisab_all,
    apply_calc_emisab_all_to_state,
    register_calc_emisab_all_source_routine,
    run_source_order_validation as run_calc_emisab_source_order_validation,
    write_calc_emisab_validation_products,
)

__all__.extend([
    "CalcEmisabPortError", "CalcEmisabWorkspace", "CalcEmisabContext",
    "CalcEmisabRecordTrace", "CalcEmisabIonTrace", "CalcEmisabElementTrace", "CalcEmisabResult",
    "resolve_calc_emisab_density", "calc_emisab_ion", "calc_emisab_element", "calc_emisab_all",
    "apply_calc_emisab_all_to_state", "register_calc_emisab_all_source_routine",
    "run_calc_emisab_source_order_validation", "write_calc_emisab_validation_products",
])

from .source_port.xstarcalc import (
    CompleteLocalXstarcalcPortError,
    CompleteLocalXstarcalcResult,
    apply_dsec_to_state,
    apply_calc_hmc_all_to_state,
    register_complete_local_xstarcalc_source_routines,
    run_complete_local_xstarcalc,
    run_complete_local_xstarcalc_validation,
    write_complete_local_xstarcalc_validation_products,
)

__all__.extend([
    "CompleteLocalXstarcalcPortError",
    "CompleteLocalXstarcalcResult",
    "apply_dsec_to_state",
    "apply_calc_hmc_all_to_state",
    "register_complete_local_xstarcalc_source_routines",
    "run_complete_local_xstarcalc",
    "run_complete_local_xstarcalc_validation",
    "write_complete_local_xstarcalc_validation_products",
])


from .source_port.physical_benchmark_suite import (
    REQUIRED_XSTAR_PRODUCTS, CANONICAL_STANDARD_CASES,
    PhysicalBenchmarkError, ParsedXSTARCommand,
    OriginalXSTARBenchmarkCase, OriginalExecutionResult,
    CasePhysicalBenchmarkResult, PhysicalBenchmarkSuiteResult,
    parse_run_xstar_script, discover_original_xstar_cases,
    select_benchmark_cases, prepare_original_xstar_suite,
    run_original_xstar_case, compare_benchmark_case,
    run_physical_benchmark_suite, write_physical_benchmark_products,
)

# Public end-to-end source-port execution API.
from .source_port.physical_runner import (
    ProgressCallback,
    XSTARPythonRunnerError,
    UnsupportedXSTARParameterError,
    XSTARPythonAcceptanceError,
    NormalizedXSTARParameters,
    XSTARPythonRunResult,
    C5NE1AcceptanceResult,
    XSTARPythonCacheResult,
    default_output_metadata_cache_path,
    save_source_output_metadata_cache,
    load_source_output_metadata_cache,
    prepare_xstar_python_cache,
    run_xstar_from_parameters,
    run_xstar_python,
    run_xstar_python_command,
    run_xstar_python_script,
    Zone1DsecDiagnosticRun,
    run_zone1_dsec_diagnostic_from_parameters,
    run_zone1_dsec_diagnostic_script,
    run_c5_ne1_acceptance,
)


for _name in (
    "default_derived_pointer_cache_path",
    "default_output_metadata_cache_path",
    "save_source_output_metadata_cache",
    "load_source_output_metadata_cache",
):
    if _name not in __all__:
        __all__.append(_name)

if "ProgressCallback" not in __all__:
    __all__.append("ProgressCallback")

for _name in (
    "XSTARPythonCacheResult", "prepare_xstar_python_cache",
    "Zone1DsecDiagnosticRun", "run_zone1_dsec_diagnostic_from_parameters",
    "run_zone1_dsec_diagnostic_script",
):
    if _name not in __all__:
        __all__.append(_name)

from .source_port.physical_output_diagnostics import (
    PhysicalMismatchDiagnosis,
    diagnose_physical_output_mismatch,
)

for _name in ("PhysicalMismatchDiagnosis", "diagnose_physical_output_mismatch"):
    if _name not in __all__:
        __all__.append(_name)
