"""Python tools for reading and evaluating XSTAR's packed ``atdb.fits`` atomic database."""

__version__ = "0.4.25"

# Pure-Python public API infrastructure.  These remain importable even on
# systems where astropy is not available yet.
from .context import LocalPlasmaState, RadiationField, EscapeContext, XSTARContext, context_from_values, context_from_xstar_run
from .rates_type50 import RateEvaluation, evaluate_type50_bound_bound, evaluate_type50_ucalc_record
from .rates_type51 import evaluate_type51_ucalc_record
from .rates_type71 import evaluate_calt71_record, evaluate_type71_ucalc_record
from .rates_type53 import Type53LiveRadiationState, Type53PhintResult, evaluate_phint53_exact, evaluate_type53_ucalc_record
from .xstar_type53_live_native_parity import build_type53_live_native_parity_audit, write_type53_live_native_parity_audit
from .xstar_priority_native_type53_integration import build_priority_native_type53_integration_audit, write_priority_native_type53_integration_audit
from .xstar_type50_type71_native_parity import (
    build_type50_type71_native_parity_audit,
    write_type50_type71_native_parity_audit,
)
from .xstar_priority_native_type50_type71_integration import (
    build_priority_native_type50_type71_integration_audit,
    write_priority_native_type50_type71_integration_audit,
)
from .audit import type50_line_pumping
from .benchmark import (
    XSTARLocalTarget,
    XSTARBenchmarkComparison,
    default_helike_benchmark_cases,
    write_default_helike_cases_csv,
    build_xstar_local_target,
    compare_solver_to_xstar_target,
    reproduce_xstar_run,
    run_xstar_benchmark_suite,
    write_xstar_benchmark_outputs,
    write_xstar_benchmark_suite,
    solver_kwargs_from_preset,
    xstar_local_state_solver_kwargs,
)

from .xstar_run import (
    XSTARInputParameters,
    XSTAROutputProductSpec,
    parse_xstar_command,
    parse_xstar_command_file,
    standard_xstar_output_products,
    xstar_recreation_plan,
    write_xstar_recreation_plan,
)
from .xstar_state import (
    XSTARContinuumState,
    XSTARLineTransferState,
    XSTARZoneState,
    XSTARRunState,
    required_live_state_fields,
    create_initial_xstar_run_state,
    create_initial_xstar_run_state_from_input,
    write_xstar_state_skeleton,
)

from .xstar_detail import (
    read_xstar_parameters_from_run_dir,
    reconstruct_bremsa_from_detal4_rows,
    reconstruct_bremsint,
    read_xstar_detail_run_state,
    summarize_xstar_detail_state,
    write_xstar_detail_state,
    pescl_xstar,
    ptmp_from_tau_xstar,
    xstar_nbinc_index,
    type50_vtherm_xstar,
    audit_xstar_detail_type50_rates,
    write_xstar_detail_type50_rate_audit,
)

from .xstar_source_provenance import (
    audit_xstar_live_bremsa_source_path,
    write_xstar_live_bremsa_source_path_audit,
    summarize_bremsa_variant_gap,
)


from .xstar_live_rate_grid_probe import (
    LiveRateGridState,
    live_rate_grid_probe_schema_rows,
    read_live_rate_grid_probe_csv,
    summarize_live_rate_grid_probe_csv,
    prepare_live_rate_grid_probe_products,
)


from .xstar_matrix_parity import (
    audit_type53_live_bremsam_phint53,
    write_type53_live_bremsam_phint53_audit,
    audit_type53_live_bremsam_matrix_replacement,
    write_type53_live_bremsam_matrix_replacement_audit,
)

from .xstar_full_parity_closure import (
    audit_source_code_equivalent_local_closure,
    write_source_code_equivalent_local_closure_audit,
    matrix_family_closure_summary,
)

from .xstar_full_parity_probes import (
    prepare_full_parity_probe_products,
    summarize_full_parity_probe_csvs,
    read_ucalc_record_probe_csv,
    read_calc_hmc_ion_matrix_probe_csv,
)

from .xstar_record_level_replay import (
    apply_record_level_ucalc_replay,
    audit_record_level_ucalc_matrix_replay,
    write_record_level_ucalc_matrix_replay_audit,
)

from .xstar_population_closure_diagnosis import (
    diagnose_population_closure_from_family_scan,
    write_population_closure_diagnosis,
)

from .xstar_population_closure_probe import (
    population_closure_probe_schema_rows,
    summarize_population_closure_probe_csv,
    write_population_closure_probe_products,
)

from .xstar_calc_hmc_all_probe import (
    calc_hmc_all_probe_helper,
    calc_hmc_all_insertion_snippets,
    write_calc_hmc_all_probe_products,
)

from .xstar_msolvelucy_state_probe import (
    msolvelucy_state_probe_helper,
    msolvelucy_insertion_snippets,
    write_msolvelucy_state_probe_products,
)

from .xstar_full_element_basis import (
    build_full_element_basis_scaffold,
    write_full_element_basis_scaffold,
)

from .source_port import (
    ElementEquilibriumError, ElementIonBlock, ElementBasisRow, ElementCompactBasis,
    EscapeProbabilityContext, ElementEquilibriumContext, MatrixTerm, IonAssemblySummary,
    ElementMatrixAssembly, LucyIterationTrace, LucySolveResult, ElementEquilibriumResult,
    build_level_table, build_element_compact_basis, levwk, levwkelement,
    assemble_element_matrix, msolvelucy, solve_element_statistical_equilibrium,
    register_element_equilibrium_stage, write_element_equilibrium_products,
    IonBalanceError, CalcIonRatesContext, CalcIonRateContribution,
    CalcIonRatesResult, IoneqmResult, IstrucResult, IonStageLimitResult,
    calc_ion_rates, ioneqm, istruc, select_ion_stage_limits,
    calc_element_pre_matrix_balance,
    CalcHMCAllError, FixedStateElementRequest, FixedStateContinuumResult,
    FixedStateElementResult, FixedStateCalcHMCAllResult,
    resolve_calc_hmc_all_density, calc_hmc_all, register_fixed_state_calc_hmc_all,
    write_fixed_state_calc_hmc_all_products,
    CalcHMCAllParityError, CalcHMCAllProbeCritfReference,
    CalcHMCAllParityRow, CalcHMCAllPreContinuumParityResult,
    load_calc_hmc_all_probe_critf, compare_calc_hmc_all_pre_continuum_probe,
    write_calc_hmc_all_pre_continuum_parity_products,
    PopulationParityError, XSTARPopulationReference, XSTARRuntimeContextReference, PopulationMetrics,
    ElementPopulationParityResult, load_xstar_population_reference, load_xstar_runtime_context_reference,
    compare_element_population_parity, write_element_population_parity_products,
    MSolveStateParityError, StateComponentMetrics, MSolveStateParityResult,
    compare_msolvelucy_state_probe, write_msolvelucy_state_parity_products,
    FullElementMatrixParityError, MatrixFamilyParityMetrics,
    FullElementMatrixParityResult, compare_full_element_matrix_probe,
    write_full_element_matrix_parity_products,
    EscapeStateError, EscapeStateBuildResult, load_escape_state_from_xstar_run,
    write_escape_state_npz, write_escape_state_summary,
)

from .workflow import (
    TripletResult,
    open_database,
    get_levels,
    get_lines,
    get_wavelengths,
    get_energies,
    match_line,
    match_lines,
    get_collisions,
    get_photoionization,
    get_recombination,
    calc_emissivity,
    calc_rate,
    calc_triplet,
    solve_populations,
    build_matrix,
)

try:
    from .hierarchy import ATDB
    from .api import XSTARAtomic, parse_ion
    from .data import download_data, find_atdb_file, get_data_path, get_data_paths, resolve_atdb_path, set_data_path
    from .xstar_element_solver import solve_element_reference
except ModuleNotFoundError as exc:  # pragma: no cover - optional dependency guard
    if exc.name != "astropy":
        raise

    def _missing_astropy(*args, **kwargs):
        raise ImportError("This xstar_atomic feature requires astropy. Install package dependencies or `pip install astropy`.")

    ATDB = _missing_astropy  # type: ignore
    XSTARAtomic = _missing_astropy  # type: ignore
    parse_ion = _missing_astropy  # type: ignore
    download_data = _missing_astropy  # type: ignore
    find_atdb_file = _missing_astropy  # type: ignore
    get_data_path = _missing_astropy  # type: ignore
    get_data_paths = _missing_astropy  # type: ignore
    resolve_atdb_path = _missing_astropy  # type: ignore
    set_data_path = _missing_astropy  # type: ignore
    solve_element_reference = _missing_astropy  # type: ignore

__all__ = [
    "ATDB",
    "XSTARAtomic",
    "parse_ion",
    "download_data",
    "find_atdb_file",
    "get_data_path",
    "get_data_paths",
    "resolve_atdb_path",
    "set_data_path",
    "solve_element_reference",
    "LocalPlasmaState",
    "RadiationField",
    "EscapeContext",
    "XSTARContext",
    "context_from_values",
    "context_from_xstar_run",
    "RateEvaluation",
    "evaluate_type50_bound_bound",
    "evaluate_type50_ucalc_record",
    "evaluate_type51_ucalc_record",
    "evaluate_calt71_record",
    "evaluate_type71_ucalc_record",
    "Type53LiveRadiationState",
    "Type53PhintResult",
    "evaluate_phint53_exact",
    "evaluate_type53_ucalc_record",
    "build_type53_live_native_parity_audit",
    "write_type53_live_native_parity_audit",
    "build_priority_native_type53_integration_audit",
    "write_priority_native_type53_integration_audit",
    "build_type50_type71_native_parity_audit",
    "write_type50_type71_native_parity_audit",
    "build_priority_native_type50_type71_integration_audit",
    "write_priority_native_type50_type71_integration_audit",
    "type50_line_pumping",
    "XSTARLocalTarget",
    "XSTARBenchmarkComparison",
    "default_helike_benchmark_cases",
    "write_default_helike_cases_csv",
    "build_xstar_local_target",
    "compare_solver_to_xstar_target",
    "reproduce_xstar_run",
    "run_xstar_benchmark_suite",
    "write_xstar_benchmark_outputs",
    "write_xstar_benchmark_suite",
    "solver_kwargs_from_preset",
    "xstar_local_state_solver_kwargs",
    "TripletResult",
    "open_database",
    "get_levels",
    "get_lines",
    "get_wavelengths",
    "get_energies",
    "match_line",
    "match_lines",
    "get_collisions",
    "get_photoionization",
    "get_recombination",
    "calc_emissivity",
    "calc_rate",
    "calc_triplet",
    "solve_populations",
    "build_matrix",
    "XSTARInputParameters",
    "XSTAROutputProductSpec",
    "parse_xstar_command",
    "parse_xstar_command_file",
    "standard_xstar_output_products",
    "xstar_recreation_plan",
    "write_xstar_recreation_plan",
    "XSTARContinuumState",
    "XSTARLineTransferState",
    "XSTARZoneState",
    "XSTARRunState",
    "required_live_state_fields",
    "create_initial_xstar_run_state",
    "create_initial_xstar_run_state_from_input",
    "write_xstar_state_skeleton",
    "read_xstar_parameters_from_run_dir",
    "reconstruct_bremsa_from_detal4_rows",
    "reconstruct_bremsint",
    "read_xstar_detail_run_state",
    "summarize_xstar_detail_state",
    "write_xstar_detail_state",
    "LiveRateGridState",
    "live_rate_grid_probe_schema_rows",
    "read_live_rate_grid_probe_csv",
    "summarize_live_rate_grid_probe_csv",
    "prepare_live_rate_grid_probe_products",
    "audit_type53_live_bremsam_phint53",
    "write_type53_live_bremsam_phint53_audit",
    "audit_type53_live_bremsam_matrix_replacement",
    "write_type53_live_bremsam_matrix_replacement_audit",
    "audit_source_code_equivalent_local_closure",
    "write_source_code_equivalent_local_closure_audit",
    "matrix_family_closure_summary",
    "apply_record_level_ucalc_replay",
    "audit_record_level_ucalc_matrix_replay",
    "write_record_level_ucalc_matrix_replay_audit",
    "population_closure_probe_schema_rows",
    "summarize_population_closure_probe_csv",
    "write_population_closure_probe_products",
    "msolvelucy_state_probe_helper",
    "msolvelucy_insertion_snippets",
    "write_msolvelucy_state_probe_products",
]

from .xstar_priority_matrix_closure import (
    build_priority_matrix_closure_audit,
    write_priority_matrix_closure_audit,
)

from .xstar_priority_conditional_solve import (
    build_priority_conditional_solve_audit,
    write_priority_conditional_solve_audit,
)


# Source-faithful full-XSTAR Python port infrastructure (v0.4 series).
from .source_port import (
    FortranArray,
    FortranRuntimeError,
    XSTARPythonState,
    XSTARSourceRoutine,
    XSTARCALC_SOURCE_ORDER,
    XSTARCALC_FIXED_STATE_ORDER,
    ZONE_SOURCE_ORDER,
    XSTARStage,
    XSTARPythonDriver,
    UnportedXSTARSourceRoutine,
    UnportedXSTARRoutine,
    UCalcDispatcher,
    default_ucalc_dispatcher,
    UCalcLevel,
    UCalcLevelTable,
    UCalcRecord,
    UCalcContext,
    UCalcStatus,
    UCalcProvenance,
    UCalcResult,
    UCalcExecutionError,
    UCalcUntranslatedBranch,
    UCalcBranchSpec,
    SourceFaithfulUCalc,
    complete_ucalc_branch_catalog,
    default_source_faithful_ucalc,
    build_ucalc_data_type_inventory,
    build_ucalc_branch_catalog_rows,
    build_ucalc_index_only_samples,
    write_ucalc_subsystem_products,
    build_source_inventory,
    write_source_inventory,
    default_port_ledger,
    AtomicDatabaseError,
    PackedRecordHeader,
    XSTARMasterData,
    XSTARDerivedPointers,
    DBWK2Instruction,
    readtbl,
    setptrs,
    dbwk2,
    load_atomic_database_state,
    register_atomic_database_stages,
    save_derived_pointer_cache,
    load_derived_pointer_cache,
    write_atomic_database_products,
    XSTARLinearAlgebraError, LUDecomposition, LinearSolveResult,
    ludcmp, lubksb, mprove, leqt2f,
    ElementEquilibriumError,
    ElementIonBlock,
    ElementBasisRow,
    ElementCompactBasis,
    EscapeProbabilityContext,
    ElementEquilibriumContext,
    MatrixTerm,
    IonAssemblySummary,
    ElementMatrixAssembly,
    LucyIterationTrace,
    LucySolveResult,
    ElementEquilibriumResult,
    build_level_table,
    build_element_compact_basis,
    levwk,
    levwkelement,
    assemble_element_matrix,
    msolvelucy,
    solve_element_statistical_equilibrium,
    register_element_equilibrium_stage,
    write_element_equilibrium_products,
    IonBalanceError,
    CalcIonRatesContext,
    CalcIonRateContribution,
    CalcIonRatesResult,
    IoneqmResult,
    IstrucResult,
    IonStageLimitResult,
    calc_ion_rates,
    ioneqm,
    istruc,
    select_ion_stage_limits,
    calc_element_pre_matrix_balance,
    CalcHMCAllError,
    FixedStateElementRequest,
    FixedStateContinuumResult,
    FixedStateElementResult,
    FixedStateCalcHMCAllResult,
    resolve_calc_hmc_all_density,
    calc_hmc_all,
    register_fixed_state_calc_hmc_all,
    write_fixed_state_calc_hmc_all_products,
    CalcHMCAllParityError,
    CalcHMCAllProbeCritfReference,
    CalcHMCAllParityRow,
    CalcHMCAllPreContinuumParityResult,
    load_calc_hmc_all_probe_critf,
    compare_calc_hmc_all_pre_continuum_probe,
    write_calc_hmc_all_pre_continuum_parity_products,
    PopulationParityError,
    XSTARPopulationReference,
    XSTARRuntimeContextReference,
    PopulationMetrics,
    ElementPopulationParityResult,
    load_xstar_population_reference,
    load_xstar_runtime_context_reference,
    compare_element_population_parity,
    write_element_population_parity_products,
    MSolveStateParityError,
    StateComponentMetrics,
    MSolveStateParityResult,
    compare_msolvelucy_state_probe,
    write_msolvelucy_state_parity_products,
)

__all__.extend([
    "FortranArray",
    "FortranRuntimeError",
    "XSTARPythonState",
    "XSTARSourceRoutine",
    "XSTARCALC_SOURCE_ORDER",
    "XSTARCALC_FIXED_STATE_ORDER",
    "ZONE_SOURCE_ORDER",
    "XSTARStage",
    "XSTARPythonDriver",
    "UnportedXSTARSourceRoutine",
    "UnportedXSTARRoutine",
    "UCalcLevel",
    "UCalcLevelTable",
    "UCalcRecord",
    "UCalcContext",
    "UCalcStatus",
    "UCalcProvenance",
    "UCalcResult",
    "UCalcExecutionError",
    "UCalcUntranslatedBranch",
    "UCalcBranchSpec",
    "SourceFaithfulUCalc",
    "complete_ucalc_branch_catalog",
    "default_source_faithful_ucalc",
    "build_ucalc_data_type_inventory",
    "build_ucalc_branch_catalog_rows",
    "build_ucalc_index_only_samples",
    "write_ucalc_subsystem_products",
    "UCalcDispatcher",
    "default_ucalc_dispatcher",
    "build_source_inventory",
    "write_source_inventory",
    "default_port_ledger",
    "AtomicDatabaseError",
    "PackedRecordHeader",
    "XSTARMasterData",
    "XSTARDerivedPointers",
    "DBWK2Instruction",
    "readtbl",
    "setptrs",
    "dbwk2",
    "load_atomic_database_state",
    "register_atomic_database_stages",
    "save_derived_pointer_cache",
    "load_derived_pointer_cache",
    "write_atomic_database_products",
    "XSTARLinearAlgebraError",
    "LUDecomposition",
    "LinearSolveResult",
    "ludcmp",
    "lubksb",
    "mprove",
    "leqt2f",
    "ElementEquilibriumError",
    "ElementIonBlock",
    "ElementBasisRow",
    "ElementCompactBasis",
    "EscapeProbabilityContext",
    "EscapeStateError",
    "EscapeStateBuildResult",
    "load_escape_state_from_xstar_run",
    "write_escape_state_npz",
    "write_escape_state_summary",
    "ElementEquilibriumContext",
    "MatrixTerm",
    "IonAssemblySummary",
    "ElementMatrixAssembly",
    "LucyIterationTrace",
    "LucySolveResult",
    "ElementEquilibriumResult",
    "build_level_table",
    "build_element_compact_basis",
    "levwk",
    "levwkelement",
    "assemble_element_matrix",
    "msolvelucy",
    "solve_element_statistical_equilibrium",
    "register_element_equilibrium_stage",
    "write_element_equilibrium_products",
    "CalcHMCAllError",
    "FixedStateElementRequest",
    "FixedStateContinuumResult",
    "FixedStateElementResult",
    "FixedStateCalcHMCAllResult",
    "resolve_calc_hmc_all_density",
    "calc_hmc_all",
    "register_fixed_state_calc_hmc_all",
    "write_fixed_state_calc_hmc_all_products",
    "CalcHMCAllParityError",
    "CalcHMCAllProbeCritfReference",
    "CalcHMCAllParityRow",
    "CalcHMCAllPreContinuumParityResult",
    "load_calc_hmc_all_probe_critf",
    "compare_calc_hmc_all_pre_continuum_probe",
    "write_calc_hmc_all_pre_continuum_parity_products",
    "PopulationParityError",
    "XSTARPopulationReference",
    "XSTARRuntimeContextReference",
    "PopulationMetrics",
    "ElementPopulationParityResult",
    "load_xstar_population_reference",
    "load_xstar_runtime_context_reference",
    "compare_element_population_parity",
    "write_element_population_parity_products",
    "MSolveStateParityError",
    "StateComponentMetrics",
    "MSolveStateParityResult",
    "compare_msolvelucy_state_probe",
    "write_msolvelucy_state_parity_products",
    "FullElementMatrixParityError",
    "MatrixFamilyParityMetrics",
    "FullElementMatrixParityResult",
    "compare_full_element_matrix_probe",
    "write_full_element_matrix_parity_products",
])

__all__.extend([
    "calc_hmc_all_probe_helper",
    "calc_hmc_all_insertion_snippets",
    "write_calc_hmc_all_probe_products",
])
