# XSTAR-PYTHON-SOURCE-CORRESPONDENCE-BEGIN
# Source correspondence:
#   Fortran: gsmooth.f90 / gsmooth2.f90
#   Role: Apply the source Gaussian smoothing branch used for nonzero turbulent broadening.
#   Relation: Source-faithful numerical translation with source active-range/integral behavior.
#   Concordance: RADIAL-001; EMIS-001
#   Qualification: accepted science revision 0.6.48.12.3.45.3.3.8; frozen C++ baseline 0.6.48.12.3.44.
# XSTAR-PYTHON-SOURCE-CORRESPONDENCE-END

"""Source-faithful translation of XSTAR ``gsmooth.f90`` and ``gsmooth2.f90``.

``gsmooth`` is the optional turbulent/thermal Gaussian convolution inserted by
``xstar.f90`` after the accepted local ``xstarcalc`` calculation and before
``heatt``.  The source wrapper applies the same helper, in order, to
``brcems``, the two rows of ``rccemis``, and ``opakc``.

The translation intentionally preserves the unusual helper semantics:

* only source bins ``3:ncn2`` are replaced; bins 1--2 and caller-owned tails
  remain unchanged;
* bins at or above 20 keV are copied without convolution;
* the plus/minus trapezoid walks, stopping tests, and ``exp(-earg)`` kernel are
  evaluated in the literal source order;
* the normalization floor and all default-real constants are rounded through
  binary32 before participating in the real(8) expressions; and
* the source wrapper copies only ``1:ncn2`` into its local RRC work arrays.

The direct validation fixture was generated by compiling the unmodified XSTAR
``gsmooth.f90`` and ``gsmooth2.f90`` with dimensions-only modules.  No probe
values are used by the production implementation.
"""
from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Mapping, Sequence

import numpy as np


XSTAR_GSMOOTH_TURBULENT_CMS = float(np.float32(1.0e5))
XSTAR_GSMOOTH_THERMAL_CMS = float(np.float32(1.29e6))
XSTAR_GSMOOTH_LIGHT_CMS = float(np.float32(3.0e10))
XSTAR_GSMOOTH_ENERGY_LIMIT_EV = float(np.float32(2.0e4))
XSTAR_GSMOOTH_EXPONENT_LIMIT = float(np.float32(30.0))
XSTAR_GSMOOTH_NORMALIZATION_FLOOR = float(np.float32(1.0e-38))


class GSmoothPortError(RuntimeError):
    """Raised when the translated smoothing source contract is invalid."""


@dataclass(frozen=True)
class GSmooth2Result:
    """Result and diagnostics for one literal ``gsmooth2`` invocation."""

    ncn2: int
    vtherm_cm_s: float
    ydat_before: np.ndarray
    ydat_after: np.ndarray
    integral_before: float
    integral_after_source_range: float
    maximum_source_index_read_one_based: int
    source_file: str = "xstar/xstarlib/src/gsmooth2.f90"


@dataclass(frozen=True)
class GSmoothResult:
    """Caller-visible result of the ``gsmooth`` wrapper."""

    ncn2: int
    temperature_1e4K: float
    turbulent_velocity_km_s: float
    vtherm_cm_s: float
    brcems_before: np.ndarray
    brcems_after: np.ndarray
    rccemis_before: np.ndarray
    rccemis_after: np.ndarray
    opakc_before: np.ndarray
    opakc_after: np.ndarray
    helper_results: tuple[GSmooth2Result, ...]
    source_file: str = "xstar/xstarlib/src/gsmooth.f90"


def _vector(values: Sequence[float], *, name: str, minimum: int) -> np.ndarray:
    arr = np.asarray(values, dtype=float).reshape(-1)
    if arr.size < int(minimum):
        raise GSmoothPortError(f"{name} is shorter than the active source range")
    if not np.all(np.isfinite(arr)):
        raise GSmoothPortError(f"{name} contains non-finite values")
    return arr


def _matrix(
    values: Sequence[Sequence[float]], *, name: str, rows: int, columns: int
) -> np.ndarray:
    arr = np.asarray(values, dtype=float)
    if arr.ndim != 2 or arr.shape[0] < int(rows) or arr.shape[1] < int(columns):
        raise GSmoothPortError(
            f"{name} must have at least shape ({int(rows)}, {int(columns)})"
        )
    if not np.all(np.isfinite(arr)):
        raise GSmoothPortError(f"{name} contains non-finite values")
    return arr


def _require_source_index(arr: np.ndarray, source_index: int, *, name: str) -> int:
    idx = int(source_index) - 1
    if idx < 0 or idx >= arr.size:
        raise GSmoothPortError(
            f"{name} lacks source index {int(source_index)} required by gsmooth2"
        )
    return idx


def thermal_turbulent_velocity_cm_s(
    temperature_1e4K: float, turbulent_velocity_km_s: float
) -> float:
    """Evaluate the literal ``gsmooth.f90`` velocity expression."""
    t = float(temperature_1e4K)
    vturbi = float(turbulent_velocity_km_s)
    if not math.isfinite(t) or t <= 0.0:
        raise GSmoothPortError("gsmooth requires positive finite temperature in 1e4 K")
    if not math.isfinite(vturbi):
        raise GSmoothPortError("gsmooth requires finite turbulent velocity")
    turbulent = vturbi * XSTAR_GSMOOTH_TURBULENT_CMS
    # Source expression: (1.29e6/sqrt(1/t)).  Keep that algebra and order.
    thermal = XSTAR_GSMOOTH_THERMAL_CMS / math.sqrt(1.0 / t)
    return (turbulent * turbulent + thermal * thermal) ** float(np.float32(0.5))


def gsmooth2(
    *,
    vtherm_cm_s: float,
    epi_eV: Sequence[float],
    ydat_before: Sequence[float],
    ncn2: int,
) -> GSmooth2Result:
    """Translate ``gsmooth2.f90`` in literal loop and mutation order."""
    n = int(ncn2)
    if n < 3:
        raise GSmoothPortError("gsmooth2 requires ncn2 >= 3")
    epi = _vector(epi_eV, name="epi", minimum=n)
    before = _vector(ydat_before, name="ydat", minimum=n)
    vtherm = float(vtherm_cm_s)
    if not math.isfinite(vtherm) or vtherm <= 0.0:
        raise GSmoothPortError("gsmooth2 requires positive finite vtherm")

    ydat = before.copy()
    prod = before.copy()
    maximum_read = n

    ydatsum1 = 0.0
    for kl in range(1, n + 1):
        idx = kl - 1
        if kl > 1:
            ydatsum1 += (
                (float(before[idx]) + float(before[idx - 1]))
                * (float(epi[idx]) - float(epi[idx - 1]))
                / 2.0
            )

    for kl in range(3, n + 1):
        idx = kl - 1
        prod[idx] = float(before[idx])
        dele = float(epi[idx]) * vtherm / XSTAR_GSMOOTH_LIGHT_CMS

        if float(epi[idx]) < XSTAR_GSMOOTH_ENERGY_LIMIT_EV:
            sum1p = 0.0
            sum2p = 0.0
            sum1m = 0.0
            sum2m = 0.0
            tmp1p = 0.0
            tmp2p = 0.0
            tmp1m = 0.0
            tmp2m = 0.0
            done1 = False
            done2 = False
            klm = 1

            while (not done1) or (not done2):
                if not done2:
                    kl2p = kl + klm
                    if kl2p >= n - 1:
                        done2 = True
                    p = _require_source_index(epi, kl2p, name="epi")
                    _require_source_index(before, kl2p, name="ydat")
                    maximum_read = max(maximum_read, kl2p)
                    tmp1po = tmp1p
                    tmp2po = tmp2p
                    earg = ((float(epi[p]) - float(epi[idx])) / dele) ** 2
                    if earg >= XSTAR_GSMOOTH_EXPONENT_LIMIT:
                        done2 = True
                    rkern = math.exp(-earg)
                    tmp1p = rkern * float(before[p])
                    tmp2p = rkern
                    sum1p += (
                        (tmp1p + tmp1po)
                        * (float(epi[p]) - float(epi[p - 1]))
                        / 2.0
                    )
                    sum2p += (
                        (tmp2p + tmp2po)
                        * (float(epi[p]) - float(epi[p - 1]))
                        / 2.0
                    )

                if not done1:
                    kl2m = kl - klm
                    if kl2m <= 3:
                        done1 = True
                    m = _require_source_index(epi, kl2m, name="epi")
                    _require_source_index(before, kl2m, name="ydat")
                    maximum_read = max(maximum_read, kl2m)
                    tmp1mo = tmp1m
                    tmp2mo = tmp2m
                    earg = ((float(epi[m]) - float(epi[idx])) / dele) ** 2
                    if earg >= XSTAR_GSMOOTH_EXPONENT_LIMIT:
                        done1 = True
                    rkern = math.exp(-earg)
                    tmp1m = rkern * float(before[m])
                    tmp2m = rkern
                    sum1m += (
                        (tmp1m + tmp1mo)
                        * abs(float(epi[m]) - float(epi[m + 1]))
                        / 2.0
                    )
                    sum2m += (
                        (tmp2m + tmp2mo)
                        * abs(float(epi[m]) - float(epi[m + 1]))
                        / 2.0
                    )

                klm += 1

            prod[idx] = (sum1p + sum1m) / max(
                XSTAR_GSMOOTH_NORMALIZATION_FLOOR, sum2p + sum2m
            )

    ydatsum2 = 0.0
    for kl in range(3, n + 1):
        idx = kl - 1
        ydat[idx] = float(prod[idx])
        if kl > 1:
            ydatsum2 += (
                (float(ydat[idx]) + float(ydat[idx - 1]))
                * (float(epi[idx]) - float(epi[idx - 1]))
                / 2.0
            )

    return GSmooth2Result(
        ncn2=n,
        vtherm_cm_s=vtherm,
        ydat_before=before.copy(),
        ydat_after=ydat,
        integral_before=ydatsum1,
        integral_after_source_range=ydatsum2,
        maximum_source_index_read_one_based=int(maximum_read),
    )


def gsmooth(
    *,
    temperature_1e4K: float,
    turbulent_velocity_km_s: float,
    epi_eV: Sequence[float],
    opakc_before: Sequence[float],
    rccemis_before: Sequence[Sequence[float]],
    brcems_before: Sequence[float],
    ncn2: int,
) -> GSmoothResult:
    """Translate the ``gsmooth.f90`` wrapper and four helper calls."""
    n = int(ncn2)
    epi = _vector(epi_eV, name="epi", minimum=n)
    opacity = _vector(opakc_before, name="opakc", minimum=n)
    rcc = _matrix(rccemis_before, name="rccemis", rows=2, columns=n)
    brems = _vector(brcems_before, name="brcems", minimum=n)
    vtherm = thermal_turbulent_velocity_cm_s(
        temperature_1e4K, turbulent_velocity_km_s
    )

    brems_result = gsmooth2(
        vtherm_cm_s=vtherm, epi_eV=epi, ydat_before=brems, ncn2=n
    )

    # The Fortran wrapper copies only 1:ncn2 into local ncn-sized work arrays.
    # The active source grid must therefore be such that gsmooth2 never depends
    # on an uninitialized local tail.  Copying the caller tail here is benign
    # only when that contract is satisfied; assert it after each helper call.
    rcc1_result = gsmooth2(
        vtherm_cm_s=vtherm, epi_eV=epi, ydat_before=rcc[0], ncn2=n
    )
    rcc2_result = gsmooth2(
        vtherm_cm_s=vtherm, epi_eV=epi, ydat_before=rcc[1], ncn2=n
    )
    for result in (rcc1_result, rcc2_result):
        if result.maximum_source_index_read_one_based > n:
            raise GSmoothPortError(
                "gsmooth2 read beyond ncn2 from a source-local RRC work array; "
                "the original Fortran value is uninitialized for this grid"
            )

    opacity_result = gsmooth2(
        vtherm_cm_s=vtherm, epi_eV=epi, ydat_before=opacity, ncn2=n
    )

    rcc_after = rcc.copy()
    rcc_after[0, :n] = rcc1_result.ydat_after[:n]
    rcc_after[1, :n] = rcc2_result.ydat_after[:n]

    return GSmoothResult(
        ncn2=n,
        temperature_1e4K=float(temperature_1e4K),
        turbulent_velocity_km_s=float(turbulent_velocity_km_s),
        vtherm_cm_s=vtherm,
        brcems_before=brems.copy(),
        brcems_after=brems_result.ydat_after,
        rccemis_before=rcc.copy(),
        rccemis_after=rcc_after,
        opakc_before=opacity.copy(),
        opakc_after=opacity_result.ydat_after,
        helper_results=(
            brems_result,
            rcc1_result,
            rcc2_result,
            opacity_result,
        ),
    )


def _direct_gsmooth_inputs() -> Mapping[str, object]:
    ncn = 32
    ncn2 = 14
    epi = np.zeros(ncn, dtype=float)
    epi[:ncn2] = np.asarray(
        [
            4800.0,
            5000.0,
            5200.0,
            5400.0,
            5600.0,
            5800.0,
            6000.0,
            6500.0,
            7500.0,
            9000.0,
            12000.0,
            16000.0,
            21000.0,
            30000.0,
        ]
    )
    for i in range(ncn2, ncn):
        epi[i] = 30000.0 + 1000.0 * float(i + 1 - ncn2)
    idx = np.arange(1.0, ncn + 1.0)
    brcems = 0.03 * idx * idx - 0.17 * idx + 1.4
    rccemis = np.empty((2, ncn), dtype=float)
    rccemis[0] = 0.07 * idx + 0.004 * idx * idx
    rccemis[1] = 1.8 - 0.05 * idx + 0.002 * idx * idx
    opakc = 1.0e-12 * (0.5 + 0.13 * idx + 0.015 * idx * idx)
    for i in range(ncn2, ncn):
        source_i = float(i + 1)
        brcems[i] = 7000.0 + source_i
        rccemis[0, i] = 8000.0 + source_i
        rccemis[1, i] = 9000.0 + source_i
        opakc[i] = 1.0e-6 + source_i * 1.0e-9
    return {
        "ncn2": ncn2,
        "temperature_1e4K": 2.5,
        "turbulent_velocity_km_s": 1.2e4,
        "epi": epi,
        "brcems": brcems,
        "rccemis": rccemis,
        "opakc": opakc,
    }


def direct_fortran_gsmooth_reference_case() -> Mapping[str, object]:
    """Frozen output from the unmodified original Fortran wrapper/helper."""
    return {
        "vtherm_cm_s": 1.2000017334362481e9,
        "brcems_active": np.asarray(
            [
                1.2599999999999998,
                1.18,
                1.1976991073810117,
                1.2638323849341289,
                1.3518778508965053,
                1.5289125261424503,
                1.4828377540450199,
                1.6764278835609623,
                1.9600019415305847,
                2.2999999999999945,
                2.7000000000000828,
                3.1600000003942088,
                4.26,
                4.8999999999999995,
            ]
        ),
        "rcc1_active": np.asarray(
            [
                0.07400000000000001,
                0.15600000000000003,
                0.288181773592419,
                0.3911623879432905,
                0.46652532933929197,
                0.5904483685221921,
                0.5718403691121937,
                0.6840114359149159,
                0.8160007353468286,
                0.9539999999999981,
                1.100000000000027,
                1.2540000001189793,
                1.5860000000000003,
                1.7640000000000002,
            ]
        ),
        "rcc2_active": np.asarray(
            [
                1.752,
                1.708,
                1.6550096543677477,
                1.620127568655895,
                1.599449311968069,
                1.5693921407923346,
                1.5715215856853104,
                1.5483928830033904,
                1.5279999306180139,
                1.5120000000000005,
                1.499999999999999,
                1.4919999999985667,
                1.488,
                1.492,
            ]
        ),
        "opakc_active": np.asarray(
            [
                6.45e-13,
                8.2e-13,
                1.1300550239507332e-12,
                1.3815930094421983e-12,
                1.5732315234581224e-12,
                1.8945020200804447e-12,
                1.8425447447545002e-12,
                2.1397052301937112e-12,
                2.500002076258365e-12,
                2.8849999999999943e-12,
                3.300000000000078e-12,
                3.745000000351204e-12,
                4.724999999999999e-12,
                5.26e-12,
            ]
        ),
    }


def _direct_gsmooth_python_result() -> GSmoothResult:
    inp = _direct_gsmooth_inputs()
    return gsmooth(
        temperature_1e4K=float(inp["temperature_1e4K"]),
        turbulent_velocity_km_s=float(inp["turbulent_velocity_km_s"]),
        epi_eV=inp["epi"],
        opakc_before=inp["opakc"],
        rccemis_before=inp["rccemis"],
        brcems_before=inp["brcems"],
        ncn2=int(inp["ncn2"]),
    )


def run_direct_fortran_gsmooth_validation(
    *, rtol: float = 2.0e-14, atol: float = 1.0e-30
) -> Mapping[str, object]:
    """Compare the Python wrapper against frozen direct-original-Fortran output."""
    inp = _direct_gsmooth_inputs()
    refs = direct_fortran_gsmooth_reference_case()
    result = _direct_gsmooth_python_result()
    n = int(inp["ncn2"])

    vtherm_ready = bool(
        np.isclose(result.vtherm_cm_s, refs["vtherm_cm_s"], rtol=rtol, atol=atol)
    )
    brcems_ready = bool(
        np.allclose(result.brcems_after[:n], refs["brcems_active"], rtol=rtol, atol=atol)
    )
    rcc1_ready = bool(
        np.allclose(result.rccemis_after[0, :n], refs["rcc1_active"], rtol=rtol, atol=atol)
    )
    rcc2_ready = bool(
        np.allclose(result.rccemis_after[1, :n], refs["rcc2_active"], rtol=rtol, atol=atol)
    )
    opakc_ready = bool(
        np.allclose(result.opakc_after[:n], refs["opakc_active"], rtol=rtol, atol=atol)
    )
    first_two_ready = bool(
        np.array_equal(result.brcems_after[:2], result.brcems_before[:2])
        and np.array_equal(result.rccemis_after[:, :2], result.rccemis_before[:, :2])
        and np.array_equal(result.opakc_after[:2], result.opakc_before[:2])
    )
    high_energy_ready = bool(
        np.array_equal(result.brcems_after[12:n], result.brcems_before[12:n])
        and np.array_equal(result.rccemis_after[:, 12:n], result.rccemis_before[:, 12:n])
        and np.array_equal(result.opakc_after[12:n], result.opakc_before[12:n])
    )
    tails_ready = bool(
        np.array_equal(result.brcems_after[n:], result.brcems_before[n:])
        and np.array_equal(result.rccemis_after[:, n:], result.rccemis_before[:, n:])
        and np.array_equal(result.opakc_after[n:], result.opakc_before[n:])
    )
    helper_order_ready = bool(len(result.helper_results) == 4)

    summary = {
        "gsmooth_translated": True,
        "gsmooth2_translated": True,
        "gsmooth_vtherm_direct_fortran_ready": vtherm_ready,
        "gsmooth_brcems_direct_fortran_ready": brcems_ready,
        "gsmooth_rccemis1_direct_fortran_ready": rcc1_ready,
        "gsmooth_rccemis2_direct_fortran_ready": rcc2_ready,
        "gsmooth_opakc_direct_fortran_ready": opakc_ready,
        "gsmooth_first_two_bins_unchanged_ready": first_two_ready,
        "gsmooth_high_energy_passthrough_ready": high_energy_ready,
        "gsmooth_caller_tail_ownership_ready": tails_ready,
        "gsmooth_helper_call_order_ready": helper_order_ready,
    }
    summary["gsmooth_direct_original_fortran_reference_ready"] = bool(
        all(value for key, value in summary.items() if key.endswith("_ready"))
    )
    return summary


__all__ = [
    "XSTAR_GSMOOTH_TURBULENT_CMS",
    "XSTAR_GSMOOTH_THERMAL_CMS",
    "XSTAR_GSMOOTH_LIGHT_CMS",
    "XSTAR_GSMOOTH_ENERGY_LIMIT_EV",
    "XSTAR_GSMOOTH_EXPONENT_LIMIT",
    "XSTAR_GSMOOTH_NORMALIZATION_FLOOR",
    "GSmoothPortError",
    "GSmooth2Result",
    "GSmoothResult",
    "thermal_turbulent_velocity_cm_s",
    "gsmooth2",
    "gsmooth",
    "direct_fortran_gsmooth_reference_case",
    "run_direct_fortran_gsmooth_validation",
]
